### ISSUE TITLE
Default all nodeSelectors to schedule to amd64 nodes

### ISSUE THREAD

**Issue by maxlemieux** [pixie-io/pixie#1073]
**Is your feature request related to a problem? Please describe.**
Pixie will try to schedule some pods to `arm64` nodes. This causes install to hang at an early point.

**Describe the solution you'd like**
Default nodeSelector for all components which require amd64 could use `"kubernetes.io/arch": "amd64"`.

**Describe alternatives you've considered**

Add patch for nodeSelector to chart config. This seems to work if added for all components.

**Comment by JamesMBartlett** [comment]
Pixie now has alpha support for ARM, so the components scheduled to arm64 nodes should work. Could you share the issues you're running into on the arm64 nodes?

**Comment by JamesMBartlett** [comment]
I'm going to close this out as we now support arm64, so it doesn't make sense to have a node selector for amd64

**Comment by maxlemieux** [comment]
Thanks James. I did not have access to the logs. I will open a new issue with details if this comes up again.
