### ISSUE TITLE
/plugin_db_updater/load_db: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found 

### ISSUE THREAD

**Issue by asasas234** [pixie-io/pixie#1084]
**Describe the bug**
When I execute the following command kustomize build k8s/cloud/public/ | kubectl apply - f 
the job component gives an error：

```
/plugin_db_updater/load_db: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /plugin_db_updater/load_db)
/plugin_db_updater/load_db: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /plugin_db_updater/load_db)
```

**To Reproduce**
https://docs.px.dev/installing-pixie/install-guides/self-hosted-pixie/ 
Follow the step-by-step instructions at the document address above.
**Expected behavior**
Normal installation

**Comment by clemenskol** [comment]
FYI, same here. I worked around by changing the container image used by the job back to an older version:

```
image: gcr.io/pixie-prod/cloud/plugin/load_db:0.0.1
```

and that did the trick.

but **NOTE** that I don't know if that has unintended side-effects. Just posting in case it's helpful
