### ISSUE TITLE
Add annotations to CatalogSource objects

### ISSUE THREAD

**Issue by m-amaresh** [pixie-io/pixie#1118]
pixie-operator-chart deploys pixie-operator-index pod. This pod is managed by pixie-operator-index CatalogSource. 
This pod prevents GKE Cluster Autoscaler (CA) to scale-down nodes as it is not associated with any Controller. To fix this we need annotation on the pod `cluster-autoscaler.kubernetes.io/safe-to-evict: "true"`

We need this annotation on CatalogSource object. 

**Who are facing this issue?**
Organizations that are using nri-bundle helm chart to install New Relic with pixie in their cluster.

**Comment by vihangm** [comment]
This has been addressed upstream (https://github.com/operator-framework/operator-lifecycle-manager/pull/2669) and pixie now uses the newer version of OLM. Note that olm isn't auto-upgraded so you will have to upgrade it manually if you already have it running.
