### ISSUE TITLE
Support loading cron scripts with no control plane

### ISSUE THREAD

**Issue by warshawd** [pixie-io/pixie#1325]
**Is your feature request related to a problem? Please describe.**
We have operational and security concerns about the control plane being hosted outside the cluster.

**Describe the solution you'd like**
We would like a way to run pixie without a dependency on the control plane, with some other in-cluster mechanism for determining what cron scripts should be run (in particular, via setting up a configmap with the script).  The changes should support both the traditional model of sourcing scripts from the control plane as well as the new model of sourcing scripts from configmaps.

**Describe alternatives you've considered**
We also considered bringing the control plane into the cluster, but initial exploration suggested that this solution would end up being too resource-intensive for our use-case.

**Additional context**
@aimichelle mentioned this as a related issue: https://github.com/pixie-io/pixie/issues/577
We have submitted a PR for these changes here: https://github.com/pixie-io/pixie/pull/1326

**Comment by aimichelle** [comment]
Completed by https://github.com/pixie-io/pixie/pull/1326.
