### ISSUE TITLE
Support non-operator deploys of Pixie

### ISSUE THREAD

**Issue by aimichelle** [pixie-io/pixie#1350]
**Is your feature request related to a problem? Please describe.**
By default, Pixie is deployed with an operator + OLM in order to manage that operator. There are ways of deploying Pixie without the operator (see https://docs.px.dev/installing-pixie/install-guides/airgap-pixie/) which are documented. However, it would be nice to also include non-operator and non-OLM deploys through `px deploy`.

**Describe the solution you'd like**
`px deploy` and other common deploy mechanisms should allow you to deploy Pixie with/without operator and with/without OLM.

**Comment by philomory** [comment]
I'd _love_ a non-operator installation via Helm as well, even when not air-gapped. In the spirit of "if you can't say anything nice", I won't share my opinions on OLM, other than to say they aren't particularly positive.

**Comment by adammw** [comment]
Would the kustomize yamls in https://github.com/pixie-io/pixie/tree/main/k8s/operator/deployment/base be considered a non-OLM version of the operator? Or does that not include all the required components?

**Comment by vihangm** [comment]
> Would the kustomize yamls in https://github.com/pixie-io/pixie/tree/main/k8s/operator/deployment/base be considered a non-OLM version of the operator? Or does that not include all the required components?

Yeah that should deploy the operator without OLM. 
Then you'd also need the CRD https://github.com/pixie-io/pixie/blob/main/k8s/operator/crd/base/px.dev_viziers.yaml and finally a vizier resource https://github.com/pixie-io/pixie/blob/main/k8s/operator/helm/templates/04_vizier.yaml that the operator will then use to deploy the rest of vizier.

**Comment by aimichelle** [comment]
Just wanted to share that you can now deploy a non-operator version of Pixie via Helm Chart!
https://docs.px.dev/installing-pixie/install-schemes/helm/#3.-deploy-pixie-deploying-non-operator-pixie 

Thanks for the patience everyone. :) Give it a try and feel free to reach out with any feedback, issues, or questions!
