### ISSUE TITLE
Make metadata service track the events/changes for a specific set of namespaces in multi-tenant clusters

### ISSUE THREAD

**Issue by MrAta** [pixie-io/pixie#1364]
**Is your feature request related to a problem? Please describe.**
Currently, metadata service keeps track of the events/changes in the entire cluster. However, the number and amount of events in big and multi-tenant clusters can make the metadata service run out of memory. As such it's desired to limit the scope of the events to a subset of the namespaces that a tenant cares about to be tracked by metadata service.

**Describe the solution you'd like**
A solution would be making the metadata service configurable to provide a list of namespaces to track the events in.

**Describe alternatives you've considered**
There's no clear alternative as of now and the metadata service runs out of memory after a while. This however seems to be a harmless event as the Pod restarts and doesn't affect the functionality of Pixie as a whole.

**Additional context**
N/A

**Comment by vihangm** [comment]
This was added and released as `release/vizier/v0.14.3`
Thanks for the contribution @MrAta
