### ISSUE TITLE
Vizier operator using etcd despite useEtcdOperator: false flag

### ISSUE THREAD

**Issue by SamuraiPrinciple** [pixie-io/pixie#1577]
**Describe the bug**
We are deploying Pixie onto EKS 1.27 using helm chart with the following values:

deployOLM: true
disableAutoUpdate: true
clusterName: props.urlSuffix
deployKey: px-dep-XXXX
useEtcdOperator: false
version: '0.13.8'

Our cluster has default storage class and EBS CSI driver installed using helm chart (but into a namespace called ebs-csi-driver).

The operator does not provision the EBS volume, but is using etcd to store Vizier metadata.

I believe this is due to this change that is overriding `useEtcdOperator` if it cannot find the CSI driver deployed in kube-system namespace:

https://github.com/pixie-io/pixie/commit/f9ee8d116046e0ec08b57f2343956c5f4fd6743e

`
_, err = clientset.AppsV1().Deployments("kube-system").Get(context.Background(), "ebs-csi-controller", metav1.GetOptions{})
`

If I create a dummy deployment called `ebs-csi-controller` in `kube-system` namespace, everything works as expected (metadata-pv-claim PVC gets provisioned and etcd goes away).

I was wondering if it'd be possible to respect `useEtcdOperator` config or have some other way (have the capability to specify the namespace where to search for ebs-csi-controller deployment) of preventing etcd to be used.

**To Reproduce**

Have EKS 1.27 cluster with aws ebs csi driver installed using Helm chart into a custom namespace.

Deploy pixie using helm chart and the following values:

deployOLM: true
disableAutoUpdate: true
clusterName: props.urlSuffix
deployKey: px-dep-XXXX
useEtcdOperator: false
version: '0.13.8'

**Expected behavior**
No etcd cluster to be provisioned.

**Logs**

time="2023-06-26T20:20:04Z" level=warning msg="No default storage class detected for cluster. Deploying etcd operator instead of statefulset for metadata backend."

**App information (please complete the following information):**
- 0.13.8
- EKS 1.27
- 5.10.179-168.710.amzn2.x86_64

**Comment by JamesMBartlett** [comment]
This should be fixed in the next operator release.

**Comment by SamuraiPrinciple** [comment]
> This should be fixed in the next operator release.

That's wonderful - thank you!
