### ISSUE TITLE
Faulty curl call in InitContainer leads to massive logs

### ISSUE THREAD

**Issue by FlorentATo** [pixie-io/pixie#1596]
**Describe the bug**
The execution of the initContainer calls the following set of bash commands:
```
    "initContainers": [
      {
        "command": [
          "sh",
          "-c",
          " set -x; URL=\"https://${SERVICE_NAME}:${SERVICE_PORT}/healthz\"; until [ $(curl -m 0.5 -s -o /dev/null -w \"%{http_code}\" -k ${URL}) -eq 200 ]; do echo \"waiting for ${URL}\" sleep 2; done; "
        ],
```
and because this is an inline command, `sleep 2` is interpreted as part of the`echo` which effectively logs as follow:
```
2023-07-05T18:44:59.572814576Z stdout F waiting for https://vizier-query-broker-svc:50300/healthz sleep 2
2023-07-05T18:44:59.572818131Z stderr F + echo 'waiting for https://vizier-query-broker-svc:50300/healthz' sleep 2
2023-07-05T18:44:59.572999909Z stderr F + curl -m 0.5 -s -o /dev/null -w '%{http_code}' -k https://vizier-query-broker-svc:50300/healthz
2023-07-05T18:44:59.576561879Z stderr F + '[' 000 -eq 200 ]
```

As long as the `vizier-query-broker` service is unreachable, the initContainer will execute curl in loop, as fast as possible, thus leading to huge amounts of logs produced on the underlying host.

To make things worse, these logs aren't forward to the console (since the container isn't ready) so the issue can only be observed by logging on the host.

**Fix:** Add the missing `;` between `echo \"waiting for ${URL}\"` and `sleep 2;`.

❌:
- https://github.com/pixie-io/pixie/blob/c092058a5172396ea9bead1e209c2ed4e2336943/k8s/vizier/base/patch_sentry.yaml#L17
- https://github.com/pixie-io/pixie/blob/c092058a5172396ea9bead1e209c2ed4e2336943/k8s/vizier/pem/base/pem_daemonset.yaml#L55
- https://github.com/pixie-io/pixie/blob/c092058a5172396ea9bead1e209c2ed4e2336943/k8s/vizier/base/kelvin_deployment.yaml#L42
- https://github.com/pixie-io/pixie/blob/c092058a5172396ea9bead1e209c2ed4e2336943/k8s/vizier/base/query_broker_deployment.yaml#L46
- https://github.com/pixie-io/pixie/blob/c092058a5172396ea9bead1e209c2ed4e2336943/k8s/vizier/sanitizer/kelvin_deployment.yaml#L23

✅:
- https://github.com/pixie-io/pixie/blob/c092058a5172396ea9bead1e209c2ed4e2336943/k8s/cloud/base/ory_auth/kratos/kratos_deployment.yaml#L165
- https://github.com/pixie-io/pixie/blob/c092058a5172396ea9bead1e209c2ed4e2336943/k8s/vizier/etcd_metadata/base/metadata_deployment.yaml#L47
- https://github.com/pixie-io/pixie/blob/c092058a5172396ea9bead1e209c2ed4e2336943/k8s/vizier/persistent_metadata/base/metadata_statefulset.yaml#L50
- https://github.com/pixie-io/pixie/blob/c092058a5172396ea9bead1e209c2ed4e2336943/k8s/vizier/bootstrap/cloud_connector_deployment.yaml#L44
- https://github.com/pixie-io/pixie/blob/c092058a5172396ea9bead1e209c2ed4e2336943/src/e2e_test/jetstream_loadtest/k8s/subscriber_deployment.yaml#L28
- https://github.com/pixie-io/pixie/blob/c092058a5172396ea9bead1e209c2ed4e2336943/src/e2e_test/protocol_loadtest/http/wrk/k8s/client_deployment.yaml#L37
- https://github.com/pixie-io/pixie/blob/c092058a5172396ea9bead1e209c2ed4e2336943/src/e2e_test/protocol_loadtest/k8s/client/client_deployment.yaml#L25

**To Reproduce**
Deploy vizier-query-broker and simulate the endpoint https://vizier-query-broker-svc:50300/healthz being unavailable.

**Expected behavior**
- `sleep` to actually 😴 !
- Bonus: Don't run bash in debug in production 👍 

**Screenshots**
N/A

**Logs**
Cf. description above. ☝️ 

**App information (please complete the following information):**
- Pixie version: Unknown
- K8s cluster version: 1.25.6
- Node Kernel version: Ubuntu 22.04.2 LTS   5.15.0-1040-azure   containerd://1.7.1+azure-1
- Browser version: N/A

**Additional context**
For what it's worth, this bug caused our AKS clusters to produce hundred of dollars/day worth of logs until we figured it out... 💸

**Comment by aimichelle** [comment]
Fixed with #1598 . Thanks @FlorentATo !
