### ISSUE TITLE
the install command from document  is wrong 

### ISSUE THREAD

**Issue by tanjunchen** [pixie-io/pixie#1651]
**Describe the bug**
According to https://docs.px.dev/installing-pixie/install-guides/self-hosted-pixie，
```
export LATEST_CLOUD_RELEASE=$(git tag | grep -Po '(?<=release/cloud/v)[^\-]*$' | sort -t '.' -k1,1nr -k2,2nr -k3,3nr | head -n 1)
```
it is not ok for mac.

<img width="1439" alt="image" src="https://github.com/pixie-io/pixie/assets/19339970/6ab411e1-373d-4aa8-ba2b-ce943d8774f4">

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens.

**Logs**
Please attach the logs by running the following command:
```
./px collect-logs
```

**App information (please complete the following information):**
- Pixie version
- K8s cluster version
- Node Kernel version
- Browser version

**Additional context**

**Comment by vihangm** [comment]
Ah good catch. Unfortunately this command was written with linux `grep` in mind and macOS's `grep` has different flags.

`export LATEST_CLOUD_RELEASE=$(git tag | perl -ne 'print $1 if /release\/cloud\/v([^\-]*)$/' | sort -t '.' -k1,1nr -k2,2nr -k3,3nr | head -n 1)` should be a system independent equivalent command.
We will update the docs with the same.
