### ISSUE TITLE
Not able to join organization after signing up with domain email id

### ISSUE THREAD

**Issue by ashishsinghclg** [pixie-io/pixie#1819]
**Describe the bug**
I have signed up in https://work.withpixie.ai/ with my domain email id ashish.singh@ginco.co.jp. I should have been added to my organization by default but I have not been added. Even my organization admin has not received invitation to add me to the organization. Instead I have been asked to create a new organization. 

Can you please help me with any of the following steps

- Add me to my organization using domain ginco.co.jp
- Delete my account from https://work.withpixie.ai/ so that I can try to sign up again

I tried contacting pixie support using chat but I did not get any response.
I even tried connecting to the slack channel but it says the invite_limit_reached

Please help me with this on urgent basis or refer me to someone who can help me with this.

<img width="1728" alt="Screenshot 2024-01-12 at 4 07 58 PM" src="https://github.com/pixie-io/pixie/assets/155618825/733dfdf0-3c47-4d2f-bfcb-5969de958157">

**Comment by ddelnano** [comment]
@aimichelle are we able to close this? If I recall correctly, you fixed this shortly after this was reported.

**Comment by ddelnano** [comment]
@ashishsinghclg closing this since I see you are in the slack. Feel free to reach out if you have any issues!
