### ISSUE TITLE
Unable to join slack. Fails on invitation

### ISSUE THREAD

**Issue by mighty1231** [pixie-io/pixie#1825]
**To Reproduce**

1. Click a slack link from README, browser opens url `https://slackin.px.dev/`
2. write my email address and click 'send invite'
3. browser sends `POST https://slackin.px.dev/invite`
4. it returns 400 error with message `invite_limit_reached`
5. no invitation email in my inbox

**Expected behavior**

http request may return 200, with an invitation email, probably?

My browser is chrome

**Comment by ashishsinghclg** [comment]
I am also facing the same issue when trying to join pixie slack.

**Comment by vihangm** [comment]
This has been fixed!
