### ISSUE TITLE
Login error Pixie Cloud

### ISSUE THREAD

**Issue by giz33** [pixie-io/pixie#1843]
**Describe the bug**
I'm trying to login with my gmail account that I created my account on Pixie, but I'm getting errors from AD login like duplicate user.
Other times I get the error that the user doesn't exist anymore..
Can someone help me please?

**To Reproduce**
1. Go to 'https://work.withpixie.ai/'
2. Click on 'Login with gmail'

**Expected behavior**
Login succeed and cluster info appears.

**Screenshots**
User doesn't exist
![image](https://github.com/pixie-io/pixie/assets/19286616/3eb20106-dde3-434b-9d0d-a277017377cc)

Duplicate user
![image](https://github.com/pixie-io/pixie/assets/19286616/e4582242-416b-4864-9821-c9ff1a889860)

**Logs**
Please attach the logs by running the following command:
```
./px collect-logs
Don't have logs
```

**App information (please complete the following information):**
- Pixie version - latest
- K8s cluster version - 1.21
- Node Kernel version - 4.15
- Browser version - Chrome 121.0.6167.185 64 bits

**Additional context**
My email = lucas.rizzi@ic*****ch.com
It worked perfectly last week, but now I can't login anymore.
I think maybe because I deleted my organization on New Relic site.If so, can anyone from New Relic restore it please? We are unable to use Pixie anymore.

Tks

**Comment by aimichelle** [comment]
Hi @giz33 ! Thanks for reaching out. This is the Github project for the open source Pixie project, which is not associated with the New Relic-hosted version of Pixie. You will have to reach out to New Relic support for some help with the login.
