### ISSUE TITLE
Upgrade OTel proto version.

### ISSUE THREAD

**Issue by etep** [pixie-io/pixie#1849]
**Is your feature request related to a problem? Please describe.**
Pixie OTel export uses an older version of the Span proto. See, e.g., the following:
1. [Example Pixie source code using older `library_spans`.](https://github.com/pixie-io/pixie/blob/f6324ceb6465a0783f690362989fcd14277aa753/src/carnot/exec/otel_export_sink_node.cc#L352)

2. [Diff in OTel repository showing deprecation of the same.](https://github.com/open-telemetry/opentelemetry-proto/pull/362/files#diff-3c3112f9fa00691754ce72f1538cc8d1829c6024a247f3ae00a01917b1554389L53-R53)

IIUC Pixie currently uses OTel proto `v0.10.0`. The latest OTel proto release is now `v1.1.0`.

OTel proto `v0.19.0` introduced a change where `library_spans` were completely rm'd, see:
https://github.com/open-telemetry/opentelemetry-proto/compare/v0.18.0...v0.19.0

**Describe the solution you'd like**
Upgrade Pixie OTel proto to `v1.1.0` or to either of `v0.18.0` or `v0.19.0`. Switch to using (e.g.) `scope_spans`.

**Describe alternatives you've considered**
As an alternative, we could keep using the older OTel proto version (i.e. do nothing).

**Comment by ddelnano** [comment]
This was completed in #1974.
