### ISSUE TITLE
ArgoCD/GitOps compatibility

### ISSUE THREAD

**Issue by jemisonf** [pixie-io/pixie#186]
**Is your feature request related to a problem? Please describe.**

We're seeing a couple issues when trying to deploy Pixie using `px deploy --extract-yaml`:
* ArgoCD applies a label `argocd.argoproj.io/instance` to all the resources it manages that is getting removed by the pixie bootstrapper, which causes ArgoCD to show those resources as out of sync
* ArgoCD uses Kubernetes `ownerReferences` to identify when a resource is created by another resource, so the resources created by the Pixie bootstrapper don't show up in ArgoCD ([docs](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#owners-and-dependents))
* We needed to manually edit the secrets file to remove sensitive data that we didn't want to commit to our git repo

**Describe the solution you'd like**
The ideal way we've found to deploy GitOps apps is when you can directly download all the manifests for app using a kustomize resource reference and then patch them as needed with kustomize resource patches. Here's how that looks for ArgoCD itself ([docs](https://argoproj.github.io/argo-cd/getting_started/)):

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argo-user-rbac.yaml
  - namespace.yaml
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v1.8.0
  ...
patchesStrategicMerge:
  - argocd-notifications-cm.yaml
  - argocd-server-svc-patch.yaml
  ...
 ```

It would be awesome if there was a path to install Pixie that way.

Another option would be if `px deploy` had an option to extract all of the YAML files for a pixie deploy, instead of just extracting the bootstrapper YAML. Then we could use ArgoCD instead of the bootstrapper to manage the state of Pixie in the cluster.

Finally, just trying to fix some of those issues individually would work. The first one -- the disappearing `argocd.argoproj.io/instance` label -- is the most concerning for us because we typically alert on the sync status of Argo apps.

I'm happy to answer any ArgoCD questions related to this.

**Describe alternatives you've considered**

We can investigate using the helm chart deploy instead via ArgoCD, but I don't think that gives us a good way to handle the deploy secret.

**Additional context**

**Comment by zasgar** [comment]
Thanks, @jemisonf. 

One note: We don't normally consider the deploy key to be a "secret" because having that does not actually let you access anything. It's primarily used to find an account to register a cluster so leaking of the deploy key will just mean that someone else can give you access to their cluster. That being said, I probably still would not check it in plain text to Git. 

We are working on two enhancements: 
1. To allow Pixie deployment without our bootstrap operator. 
2. The ability to add tags to all deployed manifests (This has been requested by others as well).

**Comment by jemisonf** [comment]
Thanks @zasgar! I think either of those solutions would solve a lot of problems for us. Good to know about the deploy key. Let me know if there's any more context I can provide here or if there's anything else we can help with.

**Comment by aimichelle** [comment]
Hi @jemisonf ! You can apply labels to your deployments by running:
`px deploy --labels=label1=key1,label2=key2`. 
This will ensure that all Pixie resources that get deployed will have the necessary labels attached.
