### ISSUE TITLE
I cannot get px cli auth token when in self-hosted mode

### ISSUE THREAD

**Issue by shengjiangfeng** [pixie-io/pixie#2007]
When i use px auth login --mannual , i cannot get auth token anywhere . I deploy pixie cloud in self-hosted mode. Can you help me?

**Comment by ddelnano** [comment]
Hi @shengjiangfeng, what happened when you loaded the URL in your browser from the `px auth login --manual` command?

**Comment by shengjiangfeng** [comment]
<img width="567" alt="image" src="https://github.com/user-attachments/assets/8dfdf07a-8588-4973-b08f-7ede634d7d31">

**Comment by ddelnano** [comment]
@shengjiangfeng you need to access the `https://work.dev.withpixie.dev:443/login?local_mode=true` webpage and it will provide the token.

**Comment by shengjiangfeng** [comment]
<img width="888" alt="image" src="https://github.com/user-attachments/assets/94e2acd6-7e3e-44c5-9250-8fab27550665">
When i copy the token in browser, it give me an error.

**Comment by shengjiangfeng** [comment]
Ok, this is good now. I used proxy in my terminal. Thanks !

**Comment by jaypce78** [comment]
@shengjiangfeng  How did you able to use proxy in terminal?I am using VM so can not able to open web browser
