### ISSUE TITLE
Cloud-proxy container fails to startup and throws an error. May be fixed by https://github.com/pixie-io/pixie/pull/2016

### ISSUE THREAD

**Issue by JerrinAndrei** [pixie-io/pixie#2017]
**Describe the bug**
Currently the nginx.conf expects the a kubernetes dns service named kube-dns.kube-system.svc.cluster.local to be existing in the cluster. If this dns service does not exist the cloud-proxy pod gets terminated on startup.

**To Reproduce**
1. Go to https://docs.px.dev/installing-pixie/install-guides/self-hosted-pixie/
2. On executing step 12 to "Deploy Pixie Cloud",
kustomize build k8s/cloud/public/ | kubectl apply -f -
The cloud proxy pod fails to start with error
"host not found in resolver kube-dns.kube-system.svc.cluster.local in /usr/local/openresty/nginx/conf/nginx.conf:43"

**Expected behavior**
Cloud proxy Pod should startup successfully with existing kube dns if any.
Every kubernetes cluster can have different kube dns service names. Also some clusters can have core-dns. So the cloud proxy service should look up for the dns service specific to the cluster in which its being setup. The control for defining this this should be given to the user. 

This might be fixed in https://github.com/pixie-io/pixie/pull/2016

**Comment by ddelnano** [comment]
This is covered by https://github.com/pixie-io/pixie/pull/2018 and will be available in the next cloud release.
