### ISSUE TITLE
Support Pixie for WSL Linux Kernel

### ISSUE THREAD

**Issue by aimichelle** [pixie-io/pixie#242]
Versions of Pixie running on systems with a WSL Linux Kernel version are having issues resolving data with K8s metadata.
Upon closer inspection, it is because the cgroup proc file paths aren't in the expected location: `/sys/fs/cgroup/cpu,cpuacct/`.

Pixie should be able to handle wsl's cgroup file path convention.

**Comment by oazizi000** [comment]
As mentioned, the host system in this case didn't have `/sys/fs/cgroup/cpu,cpuacct/` mounted. Other cgroup mounts were present, including `/sys/fs/cgroup/cpu`.

These cgroup directories are used to discover the processes that belong to a pod. Planned solution is to provide a few fallback cgroup paths in case some are not present.

**Comment by oazizi000** [comment]
The latest release (Vizier v0.7.4) has a fix that now searches `/sys/fs/cgroup/cpu` in addition to `/sys/fs/cgroup/cpu,cpuacct` for robustness.

Will leave this issue open for the moment, until we can more conclusively confirm compatibility with WSL.
