### ISSUE TITLE
Consider adding checksum/signature validation to the install process

### ISSUE THREAD

**Issue by raesene** [pixie-io/pixie#243]
**Is your feature request related to a problem? Please describe.**
Looking at the [install CLI section](https://github.com/pixie-labs/pixie#install-cli) of the README, the installation mechanism suggested for new uses is to pipe a shell script to bash. 

This could present some risks as , if an attacker can compromise the web server the script is installed on, they would be able to install malicious code on user's systems. This is the attack that was recently carried out on [codecov](https://about.codecov.io/security-update/) 

**Describe the solution you'd like**

If you want to provide an automated shell script for installation, it would be a good idea to provide hashes or signatures (perhaps using something like [cosign](https://github.com/sigstore/cosign) ) and a slightly longer set of install steps

1. download script
2. validate signature/checksum
3. run script

That way users can validate a signature prior to running the script, if they want to.

**Comment by zasgar** [comment]
@raesene, This is a great suggestion. 

We're investigating how to do this and should have something here soon.

**Comment by htroisi** [comment]
The Pixie CLI docs now include directions for a variety of install methods including directly downloading the CLI binary and validating the signature. Check out: https://docs.px.dev/installing-pixie/install-schemes/cli/#1.-install-the-pixie-cli
