### ISSUE TITLE
arm64 containers

### ISSUE THREAD

**Issue by ruckc** [pixie-io/pixie#250]
**Is your feature request related to a problem? Please describe.**
Please support arm64 container architectures.  We are unable to deploy pixie on our arm64 kubernetes cluster.

**Describe the solution you'd like**
Support multiple architecture containers, primarily amd64/arm64

**Comment by HaveFun83** [comment]
:+1:  Will be great to see multi-arch support here

**Comment by tmancill** [comment]
Also see #147.

**Comment by aimichelle** [comment]
Closing as a duplicate of https://github.com/pixie-io/pixie/issues/147. Please look at that issue to track any updates!
