### ISSUE TITLE
Failed to deploy "px" using "sudo px deploy --check=false" command

### ISSUE THREAD

**Issue by 1711raggu** [pixie-io/pixie#257]
**Describe the bug**
I used token to login into to pixie CLI and Authentication was successful. However, while deploying "px" iam getting error message as below.
Error Message: You must be logged in to perform this operation. Please run `px auth login`.

![image](https://user-images.githubusercontent.com/83962350/117668118-9d19c800-b173-11eb-8e8a-39f8112f11ce.png)

**Comment by vihangm** [comment]
@1711raggu `px` checks for auth info in the current user's homedir. When you `px auth login` the auth info is written in the current user's homedir. If you then `sudo px deploy` the CLI will look for auth in the homedir for the root user.

You shouldn't need `sudo` for a `px deploy` command but if your kubeconfig is owned by root then you might need to `sudo`, however in that scenario, I'd suggest using `sudo` for `px auth login` too.
