### ISSUE TITLE
Support for KUBECTL_CONTEXT or --kubecontext

### ISSUE THREAD

**Issue by jagoe** [pixie-io/pixie#258]
**Is your feature request related to a problem? Please describe.**
I manage my different contexts using a script that sets the `KUBECTL_CONTEXT` environment variable and - if it isn't respected - uses the `--kubecontext` (or `--kube-context`, depending on the tool) flag for each tool. This enables me to persist different contexts (and namespaces, but I'm not sure that would apply to pixie) across multiple terminal sessions.

**Describe the solution you'd like**
`px` should support `KUBECTL_CONTEXT` and/or `--kubeconfig` to select the context it should operate on.

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by jagoe** [comment]
If you agree, I'd be happy to implement the change and provide a PR.

**Comment by htroisi** [comment]
@jagoe - This is not a feature that we are planning on focusing on any time soon, so we'd be happy to accept a PR if you are interested in implementing it!

**Comment by JamesMBartlett** [comment]
The `px` command currently supports `--kubeconfig` and `KUBECONFIG` env variable, which should be sufficient to switch between different contexts.
