### ISSUE TITLE
google login hangs

### ISSUE THREAD

**Issue by Morriz** [pixie-io/pixie#269]
Trying the pixie online installer. After signing up with google, login hangs forever with:
```
Authenticating
Logging in...
```

**To Reproduce**
1. Go to signup, use google
2. Login with google

**Expected behavior**
To be logged in

**Comment by zasgar** [comment]
@Morriz , thanks for reporting this. Do you mind sharing information about your setup a bit. Specifically what was the OS of the machine running the installer, were you SSH'd, etc. Thanks!

**Comment by htroisi** [comment]
@Morriz - Is it possible you were following the wrong URL? 

Someone else just ran into this exact issue when they followed the first URL output by the CLI (outlined in red), instead of the 2nd intended URL (outlined in green): 

![image](https://user-images.githubusercontent.com/66266496/118559632-13429f80-b71d-11eb-9afa-43df7dfea7d3.png)

**Comment by Morriz** [comment]
> @Morriz , thanks for reporting this. Do you mind sharing information about your setup a bit. Specifically what was the OS of the machine running the installer, were you SSH'd, etc. Thanks!

Sure: OSX, Safari, iTerm. Running the promoted oneliner to install.

**Comment by Morriz** [comment]
> @Morriz - Is it possible you were following the wrong URL? 
> 
> 
> 
> Someone else just ran into this exact issue when they followed the first URL output by the CLI (outlined in red), instead of the 2nd intended URL (outlined in green): 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/66266496/118559632-13429f80-b71d-11eb-9afa-43df7dfea7d3.png)
> 
> 

No. The installer opened the browser.

**Comment by Morriz** [comment]
This was never solved. Anything going on there? I am still not able to run your one liner after all these months ;(

**Comment by htroisi** [comment]
@Morriz - Are you able to run `px auth login` using the CLI?

**Comment by Morriz** [comment]
No auth method works at all:
- google login: never returns
- email signup: never returns (tried different email addresses)

Always:
```
Authenticating
Logging in...
```

I have a problem with google auth using Nest Protect smoke alarms, where it is expected to sign up with an `@gmail.com` address, even though that is not documented and only found out the hard way.

I am not using any `@gmail.com` addresses here so maybe that is the issue here as well? If so, are you aware your signup is severely crippled/limited?

**Comment by vihangm** [comment]
@Morriz Auth is designed to work with GMail, GSuite as well as other email providers. Given that this is the only report of auth not working that we have seen, I wonder if some adblocker or other content blocker might be getting in the way?
Can you check the network tab and console to see if there are any errors or failed network requests?

**Comment by Morriz** [comment]
Ah, never thought about that being blocked. I just tried, and got back at the stage I have gotten before (never received email though, and always checked spam):
```
Please verify your email to continue
Check your email for a verification link.
```

I signed up using different email accounts and never gotten email back.

Here's the output of the network inspector btw: https://www.dropbox.com/s/rq5ba8f8ehswe56/Screen%20Shot%202022-01-10%20at%2018.12.04.png?dl=0

**Comment by aimichelle** [comment]
Hi @Morriz! Would you happen to be free for a quick Zoom call, by any chance? I think we're still unclear on the behavior you're seeing, so it would be great if we could walk through it together and solve this.

**Comment by Morriz** [comment]
Sure, I am open to that. When would be a good time? What time zone are you in?

**Comment by aimichelle** [comment]
Hi @Morriz , just checking back in. I reached out via email to coordinate a while back--let me know if you didn't receive it. We can also coordinate here if it's easier. I am on PST, but happy to meet during off-hours for me.

**Comment by Morriz** [comment]
PST is too far off for me (9 hour diff). But can your team not see logs from my actions? I am using maurice.faber@redkubes.com to try registration with...

**Comment by zasgar** [comment]
I'm closing this issue because it's so old. If you are still running into this issue please let us know.
