### ISSUE TITLE
Auto-close the "you can now close this window" browser page

### ISSUE THREAD

**Issue by xaf** [pixie-io/pixie#27]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add a javascript tag or something to automatically close the window after a short delay, so I don't have to actually interact with my browser during the setup. Shouldn't be complicated to add as you already control the page that's shown after the authorization :)

**Describe alternatives you've considered**
None

┆Issue is synchronized with this [Jira Task](https://pixie-labs.atlassian.net/browse/PL-1646) by [Unito](https://www.unito.io/learn-more)

**Comment by XaF** [comment]
@zasgar The auto-closing code could be added in that page: https://work.withpixie.ai/auth-complete

e.g.
```html
<!DOCTYPE html>
<html>

<head>
<meta charset="utf-8">
<title>Pixie Labs</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
</head>

<body>
<div id="root"></div>
<script type="text/javascript" src="/vendor.chunk.js"></script><script type="text/javascript" src="/main.js"></script><script>setTimeout(function() { window.close(); }, 2000)</script></body>

</html>


```
