### ISSUE TITLE
Support of other Login/Identity Providers beyond just Google 

### ISSUE THREAD

**Issue by cobookman** [pixie-io/pixie#289]
**Is your feature request related to a problem? Please describe.**
Pixie currently supports just Google Account Login. 

**Describe the solution you'd like**
Supporting other identity solutions. Be it email + password, corporate SSO, ..etc. Such-as those other options listed:
https://auth0.com/docs/connections/identity-providers-social 

**Describe alternatives you've considered**
N/A - Only Google authentication is currently supported. This requires creating a Google Gmail/Workspaces account. 

**Additional context**
Many organizations prohibit the use of Google Accounts for business use.

**Comment by shellfu** [comment]
Email and Password
Corporate SSO 

Both of these options would be ideal.

**Comment by philkuz** [comment]
Hi there, we've just released Email and Password support for Auth0! Ya'll should check it out.
