### ISSUE TITLE
Enabling configurable PEM Memory Request value

### ISSUE THREAD

**Issue by jacob-hudson** [pixie-io/pixie#293]
**Is your feature request related to a problem? Please describe.**

PEM Pods can only currently have limits configured.  This is causing an issue in our environment where nodes are not being downscaled due to Pixie requirements, due to the amount of memory requested being set to the limit.  This is currently preventing clusters from scaling in, leading to wasted resources among other issues.  

**Describe the solution you'd like**

I would like for `PEMMemoryRequest` to exist to set the memory request for PEM pods, this way cluster autoscaling functions work as intended.  

**Describe alternatives you've considered**

Setting the limit to a lower value will not work because a few pods are close to the default 2Gi limit, but most pods are well under the same limit.
**Additional context**

**Comment by nserrino** [comment]
This has been addressed in the latest releases. Make sure to deploy the latest version of Vizier, the operator, and Pixie Cloud in order for the changes to work. These are the ones in k8s/cloud/public/artifact_tracker_versions.yaml
