### ISSUE TITLE
NodeAffinity in  Pixie operator configs

### ISSUE THREAD

**Issue by kotnn** [pixie-io/pixie#300]
Hello! Is it possible to add nodeAffinity support to operator configs like this?

affinity:
nodeAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
nodeSelectorTerms:
- matchExpressions:
- key: beta.kubernetes.io/os
operator: In
values:
- linux

This can be useful if Windows nodes are olso present in kubernetes cluster. This will prevent Pixie pods to be scheduled on Windows nodes.
Thank you!

**Comment by aimichelle** [comment]
Thanks for the suggestion! We've gone ahead and applied them to our operator configs, and also our vizier YAMLs.

**Comment by cdenneen** [comment]
@aimichelle you said you applied this to your operator configs but can I ask where exactly?
Having problem with vizier-pem DS trying to run on Fargate but I don't see anywhere to set the affinity rules:

https://github.com/pixie-io/pixie/blob/main/k8s/operator/helm/values.yaml

**Comment by ddelnano** [comment]
@cdenneen would the [nodeSelector](https://github.com/pixie-io/pixie/blob/fdce3fd44f55a3079ebc282a806e77f3b1de7656/k8s/operator/helm/values.yaml#L69) nested within the `pod:` key work for you use case?

Can you explain more on the environment you are deploying Pixie to? EKS Fargate still does not support eBPF to my knowledge, so I don't believe your environment is [supported](https://docs.px.dev/installing-pixie/requirements#kubernetes-production-environments).

**Comment by cdenneen** [comment]
You can have mixed environments with Fargate, Windows and EC2 Linux so the affinity is necessary. NodeSelectors I don’t believe will work properly in this case
