### ISSUE TITLE
Stirling crashes on a k8s cluster with Kafka traffic

### ISSUE THREAD

**Issue by harold-kfuse** [pixie-io/pixie#310]
**Describe the bug**
I have a AWS EKS cluster with pixie deployed and the cluster has Kafka running. It sometimes crashes with the following error:

external/com_github_tencent_rapidjson/include/rapidjson/writer.h:464: bool rapidjson::Writer<rapidjson::GenericStringBuffer<rapidjson::UTF8<char>, rapidjson::CrtAllocator>, rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator, 0>::WriteRawValue(const rapidjson::Writer::Ch *, std::size_t) [OutputStream = rapidjson::GenericStringBuffer<rapidjson::UTF8<char>, rapidjson::CrtAllocator>, SourceEncoding = rapidjson::UTF8<char>, TargetEncoding = rapidjson::UTF8<char>, StackAllocator = rapidjson::CrtAllocator, writeFlags = 0]: Assertion `is.Peek() != '\0'' failed.

I think it's due to Kafka because if I set --stirling_enable_kafka_tracing=false, I don't encounter the above error anymore.

**Comment by zasgar** [comment]
Closing as resolved for now.
