### ISSUE TITLE
px deploy fails with "Failed to get auth credentials: too many open files"

### ISSUE THREAD

**Issue by jarrettprosser** [pixie-io/pixie#312]
**Describe the bug**
I am deploying Pixie with `px deploy` onto an AWS EKS cluster from a Mac client running px 0.6.6. The deployment fails with 
```
Pixie CLI

Running Cluster Checks:
 ✔    Kernel version > 4.14.0
 ✔    Cluster type is supported
 ✔    K8s version > 1.12.0
 ✔    Kubectl > 1.10.0 is present
 ✔    User can create namespace
 ✔    Cluster type is in list of known supported types
Installing Vizier version: 0.9.1
Generating YAMLs for Pixie
Deploying Pixie to the following cluster: <cluster name>
Is the cluster correct? (y/n) [y] : y
Found 3 nodes
 ✔    Installing OLM CRDs
 ✔    Deploying OLM
 ✔    Deploying Pixie OLM Namespace
 ✔    Installing Vizier CRD
 ✔    Deploying OLM Catalog
 ✔    Deploying OLM Subscription
 ✔    Creating namespace
 ✔    Deploying Vizier
 ✔    Waiting for Cloud Connector to come online
Waiting for Pixie to pass healthcheck
 ✔    Wait for PEMs/Kelvin
 ⠇    Wait for healthcheck
Failed to get auth credentials: open /Users/jarrettprosser/.pixie/auth.json: too many open files
Failed to get auth credentials: open /Users/jarrettprosser/.pixie/auth.json: too many open files
```
Subsequent runs of `px deploy` fail with the same error.  
Trying to deploy to a different EKS cluster succeeds.
Trying to deploy to a different cluster in a different cloud succeeds.

**To Reproduce**
Run `px deploy`.

**Expected behavior**
Pixie deploys to the cluster. 

**Logs**
[pixie_logs_20210910161728.zip](https://github.com/pixie-io/pixie/files/7141634/pixie_logs_20210910161728.zip)

**App information (please complete the following information):**
- Pixie version 0.6.6
- K8s cluster version 1.20.7
- macOS version 11.5.2

**Comment by htroisi** [comment]
Increasing the limit with `ulimit -n 10240` fixed this exact issue for me.

**Comment by jarrettprosser** [comment]
Update: I tried deleting my `auth.json` file and logging back in with `px auth login`, when I next ran `px deploy` it succeeded.

**Comment by NicklasWallgren** [comment]
I've encountered this issue as well. The `ulimit` is set as `unlimited`.
