### ISSUE TITLE
Self-hosted px-operator does not take into account TLS certificate

### ISSUE THREAD

**Issue by zinderic** [pixie-io/pixie#313]
**Describe the bug**
I followed the self-hosted steps to install Pixie instance. The cloud_deps and cloud deployed fine - all pods running. I installed the self-signed certificate in my MacOS System keychain and I can login to the web page and create password. The problem is when I px deploy.

**To Reproduce**

Edit this script to add my custom domain and run it:

./scripts/create_cloud_secrets.sh

Use kustomize to create cloud_deps.yaml and cloud.yaml

kustomize build k8s/cloud_deps/public/ > cloud_deps.yaml 
kustomize build k8s/cloud/public/ > cloud.yaml

Create plc namespace and apply the two yamls:

kubectl create ns plc
kubectl apply -f cloud_deps.yaml --namespace=plc
kubectl apply -f cloud.yaml --namespace=plc

Run dev_dns_updater:

sudo ./dev_dns_updater --domain-name="< my-custom-domain >"  --kubeconfig=$KUBECONFIG --n plc

kubectl log create-admin-job-<pod_string> -n plc

Login to <my-custom-domain> and create the admin password.

export PL_CLOUD_ADDR=< my-custom-domain >
bash -c "$(curl -fsSL https://< my-custom-domain >/install.sh)"
px deploy-key create
px deploy -k < the key from above > -y

**Expected behavior**
Now I should see my cluster deployed and instrumented but I see an error:

FATA[0361] Timed out waiting for cluster ID assignment 

When I look at the logs of vizier-operator-84c7b99594-bvwpx in the px-operator namespace I see this error:

time="2021-09-11T20:53:14Z" level=info msg="Failed to update Vizier instance" error="rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: x509: certificate signed by unknown authority\""

It seems that the certificate that was created by the ./scripts/create_cloud_secrets.sh script is not the one vizier-operator trusts.

**Logs**

I tried running 'px collect-logs' but it prints and error probably because deployment is not successful:

Cannot find running Vizier instance

**App information (please complete the following information):**

px version - 0.6.6+Distribution.de1f118.20210904032616.1
k8s version - v1.20.7

**Comment by nserrino** [comment]
Hi, 

Thanks for filing. For self-hosted Pixie, you will need to put the dev_cloud_namespace flag (see https://docs.px.dev/installing-pixie/install-guides/self-hosted-pixie/#3.-deploy-pixie). 

px deploy --dev_cloud_namespace plc

**Comment by vihangm** [comment]
For more context `scripts/create_cloud_secrets.sh` creates a CA and cert and installs the CA on your system trust. However this generated CA isn't passed into the cluster. So the pods in you cluster don't trust this CA.
Using dev_cloud_namespace tells vizier to use the cluster local addresses instead and bypasses this CA check.

If you want to use a non cluster local address for vizier<->cloud communication then we recommend using a DNS for a domain you control and getting actual SSL certs using LetsEncrypt or something similar.
