### ISSUE TITLE
Wrong license header in profiler.c

### ISSUE THREAD

**Issue by michaelgugino** [pixie-io/pixie#320]
**Describe the bug**
License specified is MIT, should be GPL.  Probably many other files with this issue, seems a bulk script was used to apply licenses to lots of files.

https://github.com/pixie-io/pixie/blob/a1ccc2f13838ecc0ecca5bff311d3f628558c3e5/src/stirling/source_connectors/perf_profiler/bcc_bpf/profiler.c

**Comment by zasgar** [comment]
Thanks for the note @michaelgugino. We are in the process of fixing them.

**Comment by zasgar** [comment]
Issue is now resolved 52043bb5305b1d1fc21ea2e6cf452f41c87a6feb. Thanks a lot for the heads up!
