### ISSUE TITLE
k3d support

### ISSUE THREAD

**Issue by hongbo-miao** [pixie-io/pixie#337]
Currently [k3d](https://k3d.io/v5.0.1/) is not listed in
https://docs.px.dev/installing-pixie/requirements/

It would be great to support it or just add in the list, thanks!

If I continue installing, it seems installing successfully.

```sh
➜ px deploy
Pixie CLI

Running Cluster Checks:
 ✔    Kernel version > 4.14.0
 ✔    Cluster type is supported
 ✔    K8s version > 1.12.0
 ✔    Kubectl > 1.10.0 is present
 ✔    User can create namespace
 ✕    Cluster type is in list of known supported types  ERR: Cluster type is not in list of known supported cluster types. Ple
 ✕    Cluster type is in list of known supported types  ERR: Cluster type is not in list of known supported cluster types. Please see: https://docs.px.dev/installing-pixie/requirements/
Some cluster checks failed. Pixie may not work properly on your cluster. Continue with deploy? (y/n) [y] : y
Installing Vizier version: 0.9.7
Generating YAMLs for Pixie
Deploying Pixie to the following cluster: k3d-west
Is the cluster correct? (y/n) [y] : y
Found 1 nodes
 ✔    Installing OLM CRDs
 ✔    Deploying OLM
 ✔    Deploying Pixie OLM Namespace
 ✔    Installing Vizier CRD
 ✔    Deploying OLM Catalog
 ✔    Deploying OLM Subscription
 ✔    Creating namespace
 ✔    Deploying Vizier
 ✔    Waiting for Cloud Connector to come online
Waiting for Pixie to pass healthcheck
 ✔    Wait for PEMs/Kelvin
 ✔    Wait for healthcheck

==> Next Steps:

Run some scripts using the px cli. For example:
- px script list : to show pre-installed scripts.
- px run px/service_stats : to run service info for sock-shop demo application (service selection coming soon!).

Check out our docs: https://docs.withpixie.ai:443.

Visit : https://work.withpixie.ai:443 to use Pixie's UI.
```

![image](https://user-images.githubusercontent.com/3375461/138357393-7174665b-3faf-4f7d-a871-f40163355a83.png)

In Pixel UI, some scripts like `px/namespaces` work:

![image](https://user-images.githubusercontent.com/3375461/138357115-c1d03b36-c03f-4959-9012-e95c69f580eb.png)

Some scripts like `px/cluster` do not work:

![image](https://user-images.githubusercontent.com/3375461/138356770-ca431b38-8bcf-47a0-869e-fdef4369b516.png)

**Comment by Hongbo-Miao** [comment]
Found more info at https://github.com/pixie-io/pixie/issues/273
and
https://pixie-community.slack.com/archives/CQ63KEVFY/p1630003944005600?thread_ts=1630001589.004300&cid=CQ63KEVFY

> Pixie currently requires access to the host kernel for eBPF. Environments where k8s is running run on bare-metal or on a VM (e.g. kvm2) meet this requirement, and so that's why Pixie works.
> In environments where there's an extra containerization layer, Pixie can't currently properly punch through to the host. That's why things like `minikube --driver=docker` or `kind` are not yet supported.
