### ISSUE TITLE
Support Deployment mapping (similar to Service/Pod)

### ISSUE THREAD

**Issue by philkuz** [pixie-io/pixie#34]
**Is your feature request related to a problem? Please describe.**
Deployments are another type of k8s object that is mostly distinct from services and pods. Most importantly, it's possible that 2+ deployments back the same service so services might not be sufficient k8s objects in the future. 

**Describe the solution you'd like**
Be able to query deployments like we query services/pods.

**Describe alternatives you've considered**
Most of the time services represent deployments 1:1, so you could use service queries to achieve what you want from Deployments.  However k8s doesn't have any enforced constraint for this and it's possible for deployments to not back a service at all.

**Additional context**

┆Issue is synchronized with this [Jira Bug](https://pixie-labs.atlassian.net/browse/PL-1660) by [Unito](https://www.unito.io/learn-more)

**Comment by iamrajiv** [comment]
Hi @philkuz, I want to contribute to this project for GSoC 2022, can you guide me on how can I get started with this project?

**Comment by aimichelle** [comment]
Hi @iamrajiv ! Thanks for your interest in this project! You should submit an application for GSoC once applications open in April. In the meantime, we recommend you try deploying Pixie yourself to see what it can currently do. You can take a look at our docs at docs.px.dev. Let me know if you have any questions!

**Comment by nserrino** [comment]
When we do this, we should add deployment as a field in the Otel plugin export scripts.

**Comment by aimichelle** [comment]
This is now supported as of https://github.com/pixie-io/pixie/commit/57d21138ea54c83d780da5cb40ee3ef52b3bdea4! PR has also been submitted to update the OTel plugin scripts.
