### ISSUE TITLE
How to deploy self hosted pixie cloud?

### ISSUE THREAD

**Issue by ark-xs** [pixie-io/pixie#345]
I tried deploying the self hosted pixie cloud into a GKE cluster by using guideline from pixie.docs . By default pixie services create internal LoadBalancer for the domain name `dev.withpixie.dev, work.dev.withpixie.dev, segment.dev.withpixie.dev, docs.dev.withpixie.dev` which I'm not able to access from outside the network. So, I manually changed the two service `cloud-proxy-service` and `vzconn-service` to external LB, but the domain names are still not accessible.

`cloud-proxy-service        LoadBalancer         10.116.14.68            35.247.191.178         56000:31810/TCP,56004:30847/TCP`    - this service in my cluster resolve the work.dev.* domain name which is giving the DNS_PROBE_FINISHED_NXDOMAIN error in my browser.

Can anyone help with this issue?

**Comment by zasgar** [comment]
Closing this and tracking in #594
