### ISSUE TITLE
[Doc issue] Self-Deploy Pixie Cloud failed with `no matches for kind "Elasticsearch" in version "elasticsearch.k8s.elastic.co/v1"`

### ISSUE THREAD

**Issue by Colstuwjx** [pixie-io/pixie#346]
**Describe the bug**
Follow the [document](https://docs.px.dev/installing-pixie/install-guides/self-hosted-pixie/), and while executing `kustomize build k8s/cloud_deps/public/ | kubectl apply -f - --namespace=plc`, it failed with:

```
...
statefulset.apps/elastic-operator created
statefulset.apps/pl-nats created
statefulset.apps/pl-stan created
validatingwebhookconfiguration.admissionregistration.k8s.io/elastic-webhook.k8s.elastic.co created
error: unable to recognize "STDIN": no matches for kind "Elasticsearch" in version "elasticsearch.k8s.elastic.co/v1"
```

**To Reproduce**
Minikube v1.23.2, macOS 10.15.7, try to install self-deploy pixie cloud by following the document.

**Expected behavior**
Should installed and deploying.

**Screenshots**

**Logs**

**App information (please complete the following information):**
- Pixie version: master branch, 6a94fd61646d1664a65f3f36a5fe69501834616d
- K8s cluster version: v1.22.2

**Additional context**

**Comment by Colstuwjx** [comment]
After following elastic community [document](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-deploy-eck.html), try executed:

```
kubectl create -f https://download.elastic.co/downloads/eck/1.8.0/crds.yaml
kubectl apply -f https://download.elastic.co/downloads/eck/1.8.0/operator.yaml
```

It fixed.

I wonder if we need to update the document or the kustomize yamls.

**Comment by vihangm** [comment]
We do include the elastic CRD and operator yamls https://github.com/pixie-io/pixie/blob/main/k8s/cloud_deps/base/elastic/operator/elastic_operator.yaml (ignore the file naming, it includes the CRDs too).

We also try to ensure that the CRDs configs are ordered before the Elasticsearch cluster config to make sure that the CustomResources are ready before the cluster is created. However it's possible that the CustomResource wasn't ready when the Elasticseach cluster config got applied by kubectl and you ran into this issue.

The easiest way to handle this scenario is to just retry the `kubectl apply`. It's idempotent and should work on a later retry.
