### ISSUE TITLE
[Doc issue] no ingress installed so dev_dns_updater did nothing

### ISSUE THREAD

**Issue by Colstuwjx** [pixie-io/pixie#347]
**Describe the bug**
I've been followed the [document](https://docs.px.dev/installing-pixie/install-guides/self-hosted-pixie) to deploy pixie cloud, and [setup-dns section](https://docs.px.dev/installing-pixie/install-guides/self-hosted-pixie#set-up-dns) would update /etc/hosts if there is any ingress rules in k8s cluster. But it didn't have!

```
➜  pixie git:(main) ✗ kubectl get ing
No resources found in default namespace.
➜  pixie git:(main) ✗ kubectl get ing -n plc
No resources found in plc namespace.
```

And it of course doesn't change anything:

```
➜  pixie git:(main) ✗ ./dev_dns_updater --domain-name="dev.withpixie.dev"  --kubeconfig=$HOME/.kube/config --n=plc
INFO[0000] DNS Entries                                   entries="dev.withpixie.dev, work.dev.withpixie.dev, segment.dev.withpixie.dev, docs.dev.withpixie.dev" service=cloud-proxy-service
INFO[0000] DNS Entries                                   entries=cloud.dev.withpixie.dev service=vzconn-service
```

It didn't change /etc/hosts file!

**To Reproduce**

**Expected behavior**
Should update /etc/hosts and we could visit `dev.withpixie.dev` in browser.

**Screenshots**

**Logs**

**App information (please complete the following information):**
- Pixie version: master branch
- K8s cluster version: minikube on macOS 10.15.7 k8s version v1.22.2

**Additional context**

**Comment by vihangm** [comment]
`dev_dns_updater` looks for `LoadBalancer` type services named `cloud-proxy-service` and `vzconn-service`
These are created by `k8s/cloud/overlays/exposed_services_ilb`

It seems like you might have changed the overlays and somehow don't have these LoadBalancers running.

Can you check the output of the following:
```
kubectl get service cloud-proxy-service -n plc
kubectl get service vzconn-service -n plc
```

If you have `jq` installed, you can also check the following:
```
kubectl get service cloud-proxy-service -n plc -o json | jq '.status.loadBalancer.ingress'
kubectl get service vzconn-service -n plc -o json | jq '.status.loadBalancer.ingress'
```
and make sure they both return valid IPs.

**Comment by Colstuwjx** [comment]
Hi @vihangm 

Thanks for your reply! I'm using minikube on macOS, and I could confirm that I did have these two services:

```
➜  pixie git:(main) ✗ kubectl get service cloud-proxy-service -n plc

NAME                  TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                       AGE
cloud-proxy-service   LoadBalancer   10.103.46.213   <pending>     443:31926/TCP,4444:30084/TCP,5555:30806/TCP   22h
➜  pixie git:(main) ✗ kubectl get service vzconn-service -n plc

NAME             TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)           AGE
vzconn-service   LoadBalancer   10.106.1.229   <pending>     51600:32410/TCP   22h
```

Besides, I didn't have the corresponding loadBalancer for those two services, as I checked the minikube's [document](https://minikube.sigs.k8s.io/docs/handbook/accessing/#loadbalancer-access), should I configure the minikube tunnel to allow loadbalancer accessible via external ip?

BTW, I chose the other way before, see #350, by deploying ingress-nginx controller, and manually applied `kustomize build k8s/cloud/overlays/exposed_services_gclb`, and correct the syntax since k8s v1.18 changed its ingress format. I also manually configured ingress-nginx certificates to cloud-proxy cert, by the following operations:

```
$ minikube addons configure ingress
-- Enter custom cert(format is "namespace/secret"): plc/cloud-proxy-tls-certs
```

I also manually configured the hosts file, added:

```
192.168.64.6     dev.withpixie.dev work.dev.withpixie.dev segment.dev.withpixie.dev docs.dev.withpixie.dev
192.168.64.6     cloud.dev.withpixie.dev
```

Therefore, I could visit https://dev.withpixie.dev and configured the passwd by the recovery link. But, as #350 said, I get stuck with `px auth login`, and even don't have a solution so far.

I hope we could update the deploy document, and revise the content according different environment, e.g. minikube, gke, aws eks, etc..

Thanks!

**Comment by vihangm** [comment]
`exposed_services_gclb` are designed for GKE with an ingress, they are unlikely to work with minikube as is.

As for minikube, I didn't get a chance to try on macOS, but I just setup pixie from scratch on minikube with kvm driver on linux. You are correct, one does need to run `minikube tunnel` to make sure the that LoadBalancers get IPs assigned but after that everything works. The UI, password reset, CLI login and pixie deploy all succeeded for me.

I'll make sure we add some information about `minikube tunnel` to the docs.

**Comment by Colstuwjx** [comment]
OK, Thank you! I'll try to install pixie with running `minikube tunnel` as well.

**Comment by Colstuwjx** [comment]
Hi @vihangm 

I've been tried to install pixie with running `minikube tunnel`, it did work well with dns-updater, and I'm able to open the browser and reset passwd. But I failed to do pixie deploy, see logs below:

```
➜  pixie git:(main) ✗ px deploy --dev_cloud_namespace plc

Pixie CLI
*******************************
* IN TESTING MODE
* 	 PL_CLOUD_ADDR=dev.withpixie.dev
*******************************

Running Cluster Checks:
 ✔    Kernel version > 4.14.0
 ✔    Cluster type is supported
 ✔    K8s version > 1.16.0
 ✔    Kubectl > 1.10.0 is present
 ✔    User can create namespace
 ✔    Cluster type is in list of known supported types
Installing Vizier version: 0.8.6
Generating YAMLs for Pixie
Deploying Pixie to the following cluster: minikube-test-cluster
Is the cluster correct? (y/n) [y] : y
Found 1 nodes
 ✔    Installing OLM CRDs
 ✔    Deploying OLM
 ✔    Deploying Pixie OLM Namespace
 ✔    Installing Vizier CRD
 ✔    Deploying OLM Catalog
 ✔    Deploying OLM Subscription
 ✔    Creating namespace
 ✔    Deploying Vizier
 ⠙    Waiting for Cloud Connector to come online
FATA[0349] Timed out waiting for cluster ID assignment
```

I could see only the nats operator pod stuck in CrashLoopBack, see logs below:

```
➜  ~ kubectl get pods -n pl
NAME                             READY   STATUS             RESTARTS      AGE
nats-operator-79b4b67559-lqfjl   0/1     CrashLoopBackOff   6 (64s ago)   7m5s
➜  ~ kubectl logs nats-operator-79b4b67559-lqfjl -n pl
time="2021-11-10T02:11:16Z" level=info msg="nats-operator Version: 0.5.0-v1alpha2+git"
time="2021-11-10T02:11:16Z" level=info msg="Git SHA: 2db81ca"
time="2021-11-10T02:11:16Z" level=info msg="Go Version: go1.11.5"
time="2021-11-10T02:11:16Z" level=info msg="Go OS/Arch: linux/amd64"
time="2021-11-10T02:11:16Z" level=info msg="nats-operator is operating at the namespace scope in the \"pl\" namespace"
E1110 02:11:16.197843       1 event.go:259] Could not construct reference to: '&v1.Endpoints{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"nats-operator", GenerateName:"", Namespace:"pl", SelfLink:"", UID:"14fccdb9-85ac-4f27-956c-98a208d927ec", ResourceVersion:"4437", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63772106725, loc:(*time.Location)(0x1fd15c0)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"control-plane.alpha.kubernetes.io/leader":"{\"holderIdentity\":\"nats-operator-79b4b67559-lqfjl\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2021-11-10T02:05:25Z\",\"renewTime\":\"2021-11-10T02:11:16Z\",\"leaderTransitions\":0}"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Subsets:[]v1.EndpointSubset(nil)}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'LeaderElection' 'nats-operator-79b4b67559-lqfjl became leader'
time="2021-11-10T02:11:16Z" level=fatal msg="unexpected error while running the main control loop: the server could not find the requested resource"
```

The other pods in each ns was ready:

```
➜  ~ kubectl get pods -n plc

NAME                                       READY   STATUS      RESTARTS   AGE
api-server-5d9845df46-txlr4                1/1     Running     0          19m
artifact-tracker-server-5d9b7f45b6-sctwr   1/1     Running     0          19m
auth-server-7b57c6965-stbgp                1/1     Running     0          19m
cloud-proxy-6b8455fddc-4ggg5               2/2     Running     0          19m
config-manager-server-58554d965b-rxncn     1/1     Running     0          19m
create-admin-job--1-rf97f                  0/1     Completed   0          19m
create-hydra-client-job--1-2h7gl           0/1     Completed   0          19m
dnsmgr-server-7fb5b7c48b-2pjjx             1/1     Running     0          19m
elastic-operator-0                         1/1     Running     0          29m
hydra-7cf59c49c6-ksz6l                     1/1     Running     0          19m
indexer-server-6c45d7d65b-5lxlk            1/1     Running     0          19m
kratos-7c549b66f4-95fgv                    1/1     Running     0          19m
pl-elastic-es-data-0                       1/1     Running     0          28m
pl-elastic-es-master-0                     1/1     Running     0          28m
pl-nats-0                                  1/1     Running     0          29m
pl-nats-1                                  1/1     Running     0          28m
pl-stan-0                                  1/1     Running     0          29m
pl-stan-1                                  1/1     Running     0          28m
postgres-5cb4875b6d-pcbx4                  1/1     Running     0          29m
profile-server-664b4697cd-98jqt            1/1     Running     0          19m
project-manager-server-5597bb454-bzlgc     1/1     Running     0          19m
scriptmgr-server-6dddf96b58-fhg4s          1/1     Running     0          19m
vzconn-server-79f6b6c5c7-5n4l8             1/1     Running     0          19m
vzmgr-server-66957dcf5-5t7ln               1/1     Running     0          19m
➜  ~ kubectl get pods -n olm

NAME                               READY   STATUS    RESTARTS   AGE
catalog-operator-8dc86744b-vj8hv   1/1     Running   0          13m
olm-operator-6d88f56b99-xvj57      1/1     Running   0          13m
➜  ~ kubectl get pods -n px-operator

NAME                                                              READY   STATUS      RESTARTS   AGE
28cc2c5100e022e83bdd16277e267642d9d4f9c490ff69906c5c63--1-btlcl   0/1     Completed   0          6m39s
pixie-operator-index-4cnrk                                        1/1     Running     0          12m
vizier-operator-7659bb44f-hkfc2                                   1/1     Running     0          6m19s
```

Is there anything missed to do?

**Comment by vihangm** [comment]
Can you `git pull` the repo and try again? My changes in 79fe81297b431276f543e22ee1008653a5e93bed should address the issues you are seeing.

(Note that you need to either redeploy all of cloud from scratch or at the very least reapply `k8s/cloud/public/artifact_tracker_versions.yaml` and then bump the `artifact-tracker-server` pod.)

**Comment by Colstuwjx** [comment]
Yes, and I met a new issue, see logs below:

```
Waiting for Pixie to pass healthcheck
 ✕    Wait for PEMs/Kelvin  ERR: Failed to schedule pems:
'vizier-pem-gd77d': '0/1 nodes are available: 1 Insufficient memory.'
Failed Pixie healthcheck error=Failed to schedule pems:
'vizier-pem-gd77d': '0/1 nodes are available: 1 Insufficient memory.'
```

I'm going to recreate a new minikube node with larger memory...

**Comment by Colstuwjx** [comment]
Failed again with healthcheck issue:

```
Waiting for Pixie to pass healthcheck
 ✔    Wait for PEMs/Kelvin
 ✕    Wait for healthcheck  ERR: timeout waiting for healthcheck
Failed Pixie healthcheck error=timeout waiting for healthcheck
```

I wonder which things the healthcheck did and why it failed.

**Comment by vihangm** [comment]
Note that the health check has a timeout and will mark it as failed if it doesn't pass however it's still possible for pixie to stabilize.
I have recently noticed that on minikube it takes a lot longer for some of the pods to come up and stabilize so the CLI deploy will make a failed health check but if you wait a few minutes and check the pod status/go to the Pixie UI, things should work.

**Comment by Colstuwjx** [comment]
Hi @vihangm 

Thanks for your help! Finally I completed the installation! I've been proposed PR [pixie-io/docs.px.dev#111](https://github.com/pixie-io/docs.px.dev/pull/111) to fix the issues I met.

**Comment by vihangm** [comment]
Closing this out since it sounds like you got things running. Docs updates have been merged.

**Comment by wsszh** [comment]
@vihangm Hi, I'm trying to install self-hosted pixie on dev k8s cluster in my company, and I find the same problem as this issue posted. Is it possible to change the service from loadbalancer to nodeport?
