### ISSUE TITLE
vzmgr-server failed to connect STAN

### ISSUE THREAD

**Issue by Emin3mU** [pixie-io/pixie#364]
**Describe the bug**
Install Self-Hosted Pixie, vzmgr-server&vzconn-server failed to connect STAN,but pl-stan is ready

**Screenshots**
```
# kubectl logs vzmgr-server-58bf7bd844-fmltv -n plc
time="2021-11-22T03:05:49Z" level=info msg="Connected to NATS" func=px.dev/pixie/src/shared/services/msgbus.MustConnectNATS file="src/shared/services/msgbus/nats.go:59" URL=pl-nats
time="2021-11-22T03:05:51Z" level=fatal msg="Failed to connect to STAN" func=px.dev/pixie/src/shared/services/msgbus.MustConnectSTAN file="src/shared/services/msgbus/stan.go:44" ClusterID=pl-stan error="stan: connect request timeout (possibly wrong cluster ID?)"
```

**Logs**
Please attach the logs by running the following command:
```
./px collect-logs
```

**App information (please complete the following information):**
- Pixie version : master
- K8s cluster version : v1.22.3
- Node Kernel version : 4.18.0
- Browser version

**Comment by tuninger** [comment]
How was this problem solved?
