### ISSUE TITLE
HTTP tracing not picking up traffic on Python3 app

### ISSUE THREAD

**Issue by mleray24** [pixie-io/pixie#370]
**Describe the bug**
Pixie does not appear to trace the HTTP traffic from this particular demo app: https://github.com/speedscale/demo-hackernews
It does pick up the network and process stats for the pod. Also, other HTTP calls made from other apps in the cluster do appear.

**To Reproduce**
1. Deploy the demo app via the yaml in the repo to a cluster running Pixie
2. Forward the port to create traffic: kubectl port-forward hndemo-<...> 8080
3. Create HTTP requests: curl 127.0.0.1:8080/test
4. Go to px/pod in the Live UI - notice that network I/O shows up but no HTTP requests.

**Expected behavior**
I expect HTTP request/response data to appear in the px/pod and px/http_data dashboards.

**Screenshots**
![image](https://user-images.githubusercontent.com/30029105/145467511-afc5963f-f89b-45c9-b6b0-d9af0de3b757.png)
![image](https://user-images.githubusercontent.com/30029105/145467571-42861fff-f5f9-490b-b1dd-0d7457b66a27.png)

**Logs**
[pixie_logs_20211209150610.zip](https://github.com/pixie-io/pixie/files/7688110/pixie_logs_20211209150610.zip)

**App information (please complete the following information):**
- Pixie version
➜  ~ git:(master) ✗ px version
Pixie CLI
0.7.1+Distribution.04212ae.20211109163321.1

- K8s cluster version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:41:42Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

- Node Kernel version
unknown

- Browser version
Chrome (latest)

**Comment by mleray24** [comment]
It makes sense that this might be an edge case because the demo app is so trivial. I'll put in this workaround. Thanks Ryan!

**Comment by oazizi000** [comment]
Fix in 7e4a9a9a5a435c0d27.
