### ISSUE TITLE
I have a domain name certificate, how to install it on the local cloud

### ISSUE THREAD

**Issue by clcc2019** [pixie-io/pixie#373]
I have a domain name certificate, how to install it on the local cloud？

**Comment by clcc2019** [comment]
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/46099295/145956907-cf4af620-a803-42ee-a457-65e34ff247c3.png">

**Comment by aimichelle** [comment]
You can take a look at these instructions for configuring Pixie Cloud with your own domain name: https://docs.px.dev/installing-pixie/install-guides/production-readiness/
