### ISSUE TITLE
self-hosted auth login error

### ISSUE THREAD

**Issue by clcc2019** [pixie-io/pixie#374]
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/46099295/146472603-0722a6c4-2d7e-416d-9404-0c1770ca1618.png">

<img width="657" alt="image" src="https://user-images.githubusercontent.com/46099295/146472761-d5c0c915-ac63-4c29-8776-cd799e799156.png">

**Comment by mmuto118** [comment]
I had the same error(400 Bad Request) just after install self-hosted pixie.
