### ISSUE TITLE
"FATAL Timed out waiting for cluster ID assignment" for AKS

### ISSUE THREAD

**Issue by Sayali1638** [pixie-io/pixie#378]
**Describe the bug**

Following the instructions on the Pixie Labs website, in conjunction with the AKS cluster setup, I'm attempting to get this working on a AKS cluster. When running px deploy, I receive "FATAL Timed out waiting for cluster ID assignment" during the step "Waiting for Cloud Connector to come online". I am on a cloudshell of azure.

**Expected behavior**
Should deploy pixie.

**Comment by htroisi** [comment]
@Sayali1638 - Based on issue https://github.com/pixie-io/pixie/issues/381, it looks like you have been able to successfully deploy. Can this issue be closed?

**Comment by Sayali1638** [comment]
yes!
