### ISSUE TITLE
Pixie URL not accessible to other user

### ISSUE THREAD

**Issue by Sayali1638** [pixie-io/pixie#381]
**Describe the bug**
The pixie deployment have been done on AKS cluster and is successful.
I am able to access the live URL of UI. My colleague is not able to access the URL as we are using the same cluster and the deployment have been done there.

Please let me know how other member can access the live pixie URL.  Installation was done using azure cloud shell

For another user tried redeploying pixie but is unaccessible now:

![image](https://user-images.githubusercontent.com/66510021/148046808-23de48da-fe7e-4f2f-b799-3dff440f3a3a.png)

**Expected behavior**
Both of us should have access to same URL and able to see the data.

**Comment by htroisi** [comment]
@Sayali1638 - I'm glad to hear that you were able to successfully deploy Pixie on AKS. Pixie only needs to be installed once on the shared cluster. To share UI access with your colleague, check out these directions: https://docs.px.dev/about-pixie/faq/#how-do-i-share-a-pixie-dashboard-with-others
