### ISSUE TITLE
How to share Pixie account with other users

### ISSUE THREAD

**Issue by Sayali1638** [pixie-io/pixie#384]
**Describe the bug**
Following the pixie [documentation](https://docs.px.dev/about-pixie/faq/#how-do-i-share-a-pixie-dashboard-with-others) I tried adding user. One of my user is unable to login and getting following error:
Details: Failed to login: cannot join org – user already belongs to another org

The user has created account and tried login.

Please let me know how do I add the user.

**Comment by htroisi** [comment]
@Sayali1638 - I responded to your message on the community slack. We recently updated our Login / Invite flow and our documentation has not been updated yet. I apologize for the inconvenience.

**Comment by htroisi** [comment]
Pixie now has features to share and manage access to your Pixie organization. For more information, see the instructions [here](https://docs.px.dev/reference/admin/user-mgmt/).
