### ISSUE TITLE
Instalation Error - "rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: context deadline exceeded\""

### ISSUE THREAD

**Issue by danilo11bruno** [pixie-io/pixie#385]
**Describe the bug**
When I try to install Pixie Lab I receive this error below.

**To Reproduce**
This error occur when I try to install inside a AKS Node.
AKS Node Version: 1.20.9

**Screenshots**
![image](https://user-images.githubusercontent.com/97469611/148816696-2329bb8b-ef4d-4459-acac-6ae54dcc2780.png)

**Comment by htroisi** [comment]
@danilo11bruno - I just noticed the `@aks-nodepool`, something that I had missed in your email. Pixie's CLI is meant to be installed on your own laptop (or the Azure cloud shell), not within a node. Once the CLI is installed, you can use it to deploy Pixie onto your AKS cluster. Just make sure that your kubeconfig points to the correct cluster.
