### ISSUE TITLE
"px auth login" Failed !

### ISSUE THREAD

**Issue by cnskylee** [pixie-io/pixie#386]
![image](https://user-images.githubusercontent.com/23625153/148899735-be8597ad-954a-4339-86cf-179e070c1b55.png)

Is that really release app or just a joke or fake app ?

**Comment by philkuz** [comment]
Hi @cnskylee looks like you found a bug in our new Login flow. Sorry that this was so frustrating, but we appreciate you taking the time to file the issue.

We'll fix the bug, but in the mean time you'll need to login directly in the UI (follow that login link without the ?local_mode query param) and create an organization.

I was able to reproduce your error and fixed the error by creating an org.

**Comment by matheusmgon** [comment]
Hi @cnskylee.
I had same problem, but my O.S is Arch Linux.
When i tried to use the command "px deploy" and "px auth login" on debian based work fine.
What S.O you are use?
If you use S.O differente that recommend, try use any other that in this [LIST](https://docs.pixielabs.ai/installing-pixie/requirements/#linux-distributions)

**Comment by philkuz** [comment]
Hi all, as of yesterday's release we fixed the problem with login from org-less users. Now the UI flow requires you to create or join an organization before continuing. 

Please let us know if you find more errors in the future.
