### ISSUE TITLE
Publish image to quay.io

### ISSUE THREAD

**Issue by pinghe** [pixie-io/pixie#391]
**Is your feature request related to a problem? Please describe.**
None

**Describe the solution you'd like**
None

**Describe alternatives you've considered**
Publish image to quay.io
pixie/pixie-operator-chart include quay.io

**Additional context**
gcr.io network unreachable

**Comment by zasgar** [comment]
Hi @pinghe, publishing to other repositories has been on our list. We hope to get this done shortly. 

Will update with a milestone shortly.

**Comment by yangvipguang** [comment]
@zasgar   We work in china , so we can't reach grc.io。please   now can images  been accessed from other repositories ?

**Comment by vihangm** [comment]
We now mirror our images to quay.io among other registries. See https://quay.io/organization/pixie
We will work on making it easier to deploy pixie with custom registries but the mirroring is done.
