### ISSUE TITLE
Provide deployKey via kubernetes secret

### ISSUE THREAD

**Issue by benreynolds-drizly** [pixie-io/pixie#400]
**Is your feature request related to a problem? Please describe.**

We are deploying pixie as part of the New Relic [nri-bundle](https://github.com/newrelic/helm-charts/tree/master/charts/nri-bundle) via ArgoCD. Since this pixie helm chart does not support passing `deployKey` via a secret, we are required to hardcode the key in our git repo watched by ArgoCD.

**Describe the solution you'd like**

I would like the option to provide `deployKey` to the helm chart via a secret, something like:

```yaml
deployKeySecretName: my-custom-kubernetes-secret
deployKeySecretKey: deploy-key
```

**Describe alternatives you've considered**

I dug through the code in this repo and it doesn't look as though any alternative is really viable.

**Additional context**

N/A

**Comment by LevitatingKraken** [comment]
This is highly required, please add this option

**Comment by aimichelle** [comment]
You can now specify a custom secret for your deploy key in the helm chart:
```
customDeployKeySecret: my-custom-kubernetes secret
```

However, we expect the key to be `deploy-key`, and this is not customizable yet.
