### ISSUE TITLE
HTTP/2 traffic in https mode is not being traced

### ISSUE THREAD

**Issue by FrimIdan** [pixie-io/pixie#402]
**Describe the bug**
Following a thread in [slack](https://pixie-community.slack.com/archives/CQ63KEVFY/p1644247207106899) @oazizi000 and @chengruizhe discovered that HTTP/2 traffic in https mode is not being traced properly. 

**To Reproduce**
1. Deploy [GO demo app](https://github.com/FrimIdan/go-https-demo-app) in a K8s environment. 
2. Look for HTTPs traffic in Pixie UI

**Expected behavior**
I would expect to see the https traffic

**App information:**
- Pixie version
```
$ px version
Pixie CLI
0.7.2+Distribution.91e72cd.20211217211220.1
```
- K8s cluster version
```
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.12-gke.1500", GitCommit:"d32c0db9a3ccd0ac73b0b3abd0532505217b376e", GitTreeState:"clean", BuildDate:"2021-11-17T09:30:02Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by oazizi000** [comment]
@FrimIdan We have a fix for this that's on its way (thanks to @chengruizhe). Essentially, this case turned out to be an instance of a Go program generating HTTP/2 traffic using Go's `net/http` library (vs the alternative `net/http2` library). We actually support both, but because of a bug, the uprobes were not getting properly deployed on the `net/http` instances in some binaries, including the one here.

Stay tuned for the fix.

**Comment by oazizi000** [comment]
@FrimIdan Have you had a chance to check whether the latest release has fixed the issue for you?

**Comment by FrimIdan** [comment]
@oazizi000 Sorry for the late response, I've tested the fix and it did solved the issue.
For some reason I see the same req/resp body multiple times but it might be an issue with my demo app. (it suppose to be req-`{"body":"test"}` and resp-`{"id":1}`)
```
{
time_: 1649681859626,
source: {
  label: default/https-client-77b4d59b5d-v8bsq,
  script: px/pod,
  args: {
    start_time: -5m,
    pod: default/https-client-77b4d59b5d-v8bsq
  }
},
destination: {
  label: default/server-7d4f5b4d7d-s56pj,
  script: px/pod,
  args: {
    start_time: -5m,
    pod: default/server-7d4f5b4d7d-s56pj
  }
},
latency: 1175920,
major_version: 2,
req_path: /api/test,
req_method: POST,
req_headers: {
  :authority: server:8433,
  :method: POST,
  :path: /api/test,
  :scheme: https,
  accept: application/json,
  accept-encoding: gzip,
  content-length: 16,
  content-type: application/json,
  user-agent: Go-http-client/2.0,
  x-api-key: allow
},
req_body: {"body":"test"}
  {"body":"test"}
  {"body":"test"}
  {"body":"test"}
  {"body":"test"}
  ,
req_body_size: 80,
resp_status: 201,
resp_message: OK,
resp_headers: {
  :status: 201,
  content-length: 9,
  content-type: application/json,
  date: Mon, 11 Apr 2022 12:57:39 GMT
},
  resp_body: {"id":1}
  {"id":1}
  {"id":1}
  {"id":1}
  {"id":1}
  ,
resp_body_size: 45
}
```
