### ISSUE TITLE
HTTPs traffic is not being traced

### ISSUE THREAD

**Issue by FrimIdan** [pixie-io/pixie#403]
**Describe the bug**
Python HTTPs demo application is not being traced properly.
The python app is based on https://github.com/pixie-io/pixie-demos/tree/main/openssl-tracer/ssl_client_server

**To Reproduce**
1. Deploy [python demo app](https://github.com/FrimIdan/python-https-demo-app) in a K8s environment. 
2. Look for HTTPs traffic in Pixie UI

**Expected behavior**
I would expect to see the https traffic

**App information:**
- Pixie version
```
$ px version
Pixie CLI
0.7.2+Distribution.91e72cd.20211217211220.1
```
- K8s cluster version
```
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.12-gke.1500", GitCommit:"d32c0db9a3ccd0ac73b0b3abd0532505217b376e", GitTreeState:"clean", BuildDate:"2021-11-17T09:30:02Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by chengruizhe** [comment]
Hi @FrimIdan,
It seems like the python demo app is just sending raw messages across the network without using HTTP. 
`conn.send("Server secret {} is {}".format(count, secret).encode())` sends the string directly through a socket without HTTP headers. As a result, Stirling can't classify the type of traffic and is thus not tracing it.
You should starting seeing the traffic after modifying the app to use a HTTP library. :)

**Comment by FrimIdan** [comment]
Hi @chengruizhe,
Thanks for the feedback, I just used https://github.com/pixie-io/pixie-demos/blob/main/openssl-tracer/ssl_client_server/client.py from `pixie-io` repo and thought it should work since it uses openssl.
So, if not using HTTP library, under which filter I see that connection?

**Comment by chengruizhe** [comment]
Hi @FrimIdan,
The list of protocols supported by Pixie is [here](https://docs.px.dev/about-pixie/data-sources/#supported-protocols). Pixie doesn't parse/show raw bytes on a connection. The `openssl-tracer` demo uses openssl, but not HTTP. You need to modify the app to use an HTTP library for data to show up under the HTTP table. This can be done as described in [this stackoverflow post](https://stackoverflow.com/questions/19705785/python-3-simple-https-server).

**Comment by FrimIdan** [comment]
@chengruizhe Thanks for the clarification.
