### ISSUE TITLE
Missing services and pods

### ISSUE THREAD

**Issue by mottetm** [pixie-io/pixie#409]
**Describe the bug**
I've successfully deployed the operator on my EKS cluster and it appears as healthy on the dashboard (screenshot 1), however, most of the services/pods that are on the cluster do not appear in the dashboard.
Some examples are shown in the screenshots 2 and 3 where the services/pods listed by `kubectl` are absent from the dashboard.

**Screenshots**
![image](https://user-images.githubusercontent.com/2412973/156039634-a9343691-a8af-4646-b5c0-8e246ff2b891.png)

![image](https://user-images.githubusercontent.com/2412973/156033478-74e6652e-c870-4fa6-91c7-b26616d3602d.png)
![image](https://user-images.githubusercontent.com/2412973/156033507-df8190c2-7e5c-4216-8e08-8a35101365fc.png)

**App information (please complete the following information):**
- Pixie deployed using `pixie-operator-chart-0.0.19`
- K8s cluster version: 1.21
- Node Kernel version: 5.4.129-63.229.amzn2.x86_64

**Comment by chengruizhe** [comment]
Hi @mottetm,
Thanks for reporting this issue! I deployed argo-cd on GKE, but everything seems to be working okay.
I'm working on replicating the issue on EKS, and will reach out to you on our Community Slack (slackin.px.dev) for details and questions.

**Comment by chengruizhe** [comment]
Hi @mottetm,
I'm still unable to reproduce the same issue on EKS. I can see all the services and pods with Pixie and argocd deployed on my EKS cluster. If you are still having this issue, could you please provide detailed steps on how to reproduce? Also happy to talk on our Community Slakc (slackin.px.dev). Thanks!

**Comment by mottetm** [comment]
Hi @chengruizhe, the data ended up appearing several hours after the deployment. Sorry for the disturbance and late reaction and thanks for taking the time.
