### ISSUE TITLE
Precise time windows for http_events table

### ISSUE THREAD

**Issue by stoposto** [pixie-io/pixie#410]
**Is your feature request related to a problem? Please describe.**

I would like to be able to retrieve records in precise intervals from the `http_events` table. This would be useful when getting batch data to ensure no record is missed or duplicated. 

**Describe the solution you'd like**

I believe this could be achieved by allowing absolute timestamps to be entered for `start_time` or alternatively; allowing types `INT64` and `TIME64NS` to be logically compared, enabling records to be filtered based on a provided condition. 

**Describe alternatives you've considered**

Currently, I am recording the timestamp of the last record in the previous batch, converting it to an absolute string, e.g. "-20s" by subtracting the current time, and setting `start_time` to this in the subsequent request. 

If there is some other way around this I'd love to know 🙏

**Comment by htroisi** [comment]
Hi @stoposto! You can use absolute timestamps in the format `"2020-07-13 18:02:5.00 +0000"` for both`start_time` and `end_time`. Check out the PxL DataFrame [reference docs ](https://docs.px.dev/reference/pxl/operators/dataframe.dataframe/) for more info.

**Comment by nserrino** [comment]
One more option is you can provide start_time in nanos, such as start_time=1646157769000000000

**Comment by htroisi** [comment]
Note that the nanos solution @nserrino suggests only works from within a PxL script. The Live UI `start_time` argument wont accept nanos.
