### ISSUE TITLE
`px auth login` hangs on the `Logging in` screen

### ISSUE THREAD

**Issue by shashikiran-pdi** [pixie-io/pixie#411]
**Describe the bug**
Not able to login to px cli

**To Reproduce**
1. Run command `px auth login`
2. Opens web browser and prompts for login
3. Login to pixie

Stuck in this screen

**Expected behavior**
Pixie login flow should be complete on terminal

**Screenshots**

Browser
![image](https://user-images.githubusercontent.com/93903845/156209108-f6d7daf4-1932-42e6-8da6-d1fe0204812b.png)

Terminal
![image](https://user-images.githubusercontent.com/93903845/156209157-b6a36e4d-6bb8-450e-8990-be6a06b08071.png)

**Logs**
None

**App information (please complete the following information):**
Pixie CLI
0.7.4+Distribution.c42f675.20220216070246.1

Browser
Brave
[Version 1.35.104 Chromium: 98.0.4758.109 (Official Build) (x86_64)](https://brave.com/latest/)

**Additional context**
I tried the same on a centos machine, it worked fine since it does not open a browser

**Comment by philkuz** [comment]
Thanks for highlighting this. We're having trouble reproducing the error. If you have a chance can you run this with DevTools network tab, specifically for localhost connections during the login process? 

I saw a successful connection on my side:
<img width="746" alt="image" src="https://user-images.githubusercontent.com/5456019/157949303-d3fb1c50-fd10-477f-8156-4d0ec7691388.png">

For context, the Pixie CLI opens up a server to receive the access_token from the web client. Something is probably breaking during that handshake.

As a temporary work-around, you can use the head-less login (you saw this on centos) 
```
px auth login --manual
```

**Comment by shashikiran-pdi** [comment]
@philkuz Thanks for the reply.

I tried with my dev tools open. Found some calls being blocked. Turns out, the issue was with my Brave browser.

I turned the shields off and it worked. You can close the ticket

**Comment by shashikiran-pdi** [comment]
And FYI, the manual flag is not mentioned in the `px -h` or `px auth -h`

It would help if that is added to documentation
