### ISSUE TITLE
No Kafka data available

### ISSUE THREAD

**Issue by neuwerld2** [pixie-io/pixie#412]
**Describe the bug**
After installing Pixie in our Kubernetes cluster there seems to be no data available when running the Kafka scripts, it's empty.
I used the installation scenario for Helm described in the documentation https://docs.px.dev/installing-pixie/install-schemes/helm and I can see data from other scripts than Kafka, we are running Kafka using Strimzi.
At the moment the rates for Kafka are like the following:
65kb/s incoming
80kb/s outgoing
~270 messages per second incoming

**To Reproduce**
1. Install Pixie according to Helm instructions on https://docs.px.dev/installing-pixie/install-schemes/helm
2. Go to https://work.withpixie.ai/ and run Kafka scripts

**Expected behavior**
I expected to see data from the Kafka cluster that we are running in the k8s cluster when running the Kafka scripts in the same way I can when running other scripts available.

**Screenshots**
![pixie_kafka](https://user-images.githubusercontent.com/7700416/156899121-1597157c-bd2c-41bb-a672-9f036c1bff26.png)

**Logs**
[pixie_logs_20220305212109.zip](https://github.com/pixie-io/pixie/files/8191428/pixie_logs_20220305212109.zip)
```

**App information (please complete the following information):**
- Pixie operator v0.0.19
- K8s 1.22.4 (AKS)
- Node Kernel version 5.4.0-1065-azure
- Browser Google chrome 98.0.4758.80 (Official Build) (64-bit)
- Strimzi Kafka 0.24.0 and Kafka version 2.7.0

**Additional context**
Add any other context about the problem here.

**Comment by htroisi** [comment]
@neuwerld2 - as a first step in debugging, could you try installing Pixie's Kafka demo? 

You can install the demo in one of two ways:
1. [Install Pixie's CLI](https://docs.px.dev/installing-pixie/install-schemes/cli/#1.-install-the-pixie-cli) and run `px demo deploy px-kafka`. 
OR 
2. Clone the Pixie repo and run `kubectl apply -f .` in the `pixie/demos/kafka` folder. 

Once you've deployed the demo, could you let us know if you can see anything when you run the `px/kafka_data` script?

**Comment by neuwerld2** [comment]
Tried installing the Kafka demo using both the separate yaml file from Github and using the PX CLI, but it Zookeeper throws me "Missing privilege separation directory: /var/run/sshd" when trying to start so in keeps restarting.

**Comment by htroisi** [comment]
Hmm. I haven't run into this error before. Are you able to run `mkdir -p /var/run/sshd`?

**Comment by neuwerld2** [comment]
I am not able to because the container never get to the Running state, it keeps looping from Error to CrashLoopBackOff.
zookeeper-6c7dfd4bd6-c2lsv   0/1     ContainerCreating   0          11s
zookeeper-6c7dfd4bd6-c2lsv   0/1     Error               0          47s
zookeeper-6c7dfd4bd6-c2lsv   0/1     Error               1 (2s ago)   48s
zookeeper-6c7dfd4bd6-c2lsv   0/1     CrashLoopBackOff    1 (1s ago)   49s
zookeeper-6c7dfd4bd6-c2lsv   0/1     Error               2 (16s ago)   64s
zookeeper-6c7dfd4bd6-c2lsv   0/1     CrashLoopBackOff    2 (1s ago)    65s
zookeeper-6c7dfd4bd6-c2lsv   0/1     Error               3 (29s ago)   93s
zookeeper-6c7dfd4bd6-c2lsv   0/1     CrashLoopBackOff    3 (15s ago)   107s
zookeeper-6c7dfd4bd6-c2lsv   0/1     Error               4 (49s ago)   2m21s
zookeeper-6c7dfd4bd6-c2lsv   0/1     CrashLoopBackOff    4 (14s ago)   2m34s
zookeeper-6c7dfd4bd6-c2lsv   0/1     Error               5 (91s ago)   3m51s
zookeeper-6c7dfd4bd6-c2lsv   0/1     CrashLoopBackOff    5 (12s ago)   4m3s

**Comment by neuwerld2** [comment]
Managed to get Zookeeper up and running by changing version to latest (not sure if this made all the difference) and then constantly beating mkdir command. After it came up I can see data when running Kafka scripts in Pixie.

**Comment by htroisi** [comment]
Just to clarify - are you seeing the `px-kafka` demo data or data from your applications?

**Comment by chengruizhe** [comment]
Hi @neuwerld2,
Thank you for reporting this issue!
From the logs, it seems like Pixie is tracing many Kafka connections. Do you see any data in the `kafka_data` table? Could you please also double check that you are on the correct cluster, and try setting a longer `start_time`?

On my cluster, I deployed [this strimzi demo](https://github.com/strimzi/client-examples) and I can see all the data in Pixie. 
If would be great if you could provide a demo app / instructions on how to reproduce, so that I could take a look.

**Comment by neuwerld2** [comment]
To clearify, i saw data from px-demo.
Tried setting like 60m or 2h in start_time and still nothing, also tried different kafka scripts.
When it comes to demo app, i could probably give you the kubernetes yaml that we are using.

**Comment by neuwerld2** [comment]
We are using the Strimzi Operator from [here](https://github.com/strimzi/strimzi-kafka-operator/tree/main/helm-charts/helm3/strimzi-kafka-operator).
And here is a yaml file with the cluster and some dependencies that we use:
[strimzi-kafka.zip](https://github.com/pixie-io/pixie/files/8215076/strimzi-kafka.zip)

**Comment by chengruizhe** [comment]
@neuwerld2 Could try the following and see if you can see traffic?
1. Deploy Pixie with helm or `px deploy`
2. Deploy the Strimzi Operator: 
`helm install my-release strimzi/strimzi-kafka-operator --version 0.25.0`
3. Deploy the Kafka cluster with this yaml: [simple_kafka.yaml.zip](https://github.com/pixie-io/pixie/files/8219654/simple_kafka.yaml.zip)
`kubectl apply -f simple_kafka.yaml`
4. In one console:
`kubectl -n kafka run kafka-producer -ti --image=quay.io/strimzi/kafka:0.25.0-kafka-2.7.0 --rm=true --restart=Never -- bin/kafka-console-producer.sh --broker-list my-cluster-kafka-bootstrap.default.svc:9092 --topic my-topic`
5. In another console:
`kubectl -n kafka run kafka-consumer -ti --image=quay.io/strimzi/kafka:0.25.0-kafka-2.7.0 --rm=true --restart=Never -- bin/kafka-console-consumer.sh --bootstrap-server my-cluster-kafka-bootstrap.default.svc:9092 --topic my-topic --from-beginning`
6. You should be able to type messages into the producer and see messages from the consumer in the other console.
7. Go to the Pixie UI, and check the `kafka_data` script. You should see records in the table.
Please let me know if this works for you. Thanks!

**Comment by neuwerld2** [comment]
I need to go through this so that I don't mess up what i already have installed in my cluster since i am already running the operator and 2 clusters. I would be very surprised if this worked since I already have Kafka from Strimzi installed in my cluster.

**Comment by chengruizhe** [comment]
Closed for now due to inactivity and difficulty to reproduce.
