### ISSUE TITLE
Document --manual flag for px auth login

### ISSUE THREAD

**Issue by philkuz** [pixie-io/pixie#414]
> And FYI, the manual flag is not mentioned in the `px -h` or `px auth -h`

> It would help if that is added to documentation

_Originally posted by @shashikiran-pdi in https://github.com/pixie-io/pixie/issues/411#issuecomment-1065824597_

Some users have issues with auto-login, especially with tools like uBlock, Brave, etc that block outgoing connections from the browser.

We should document manual login in the CLI and the docs.

**Comment by htroisi** [comment]
The `--manual` flag is documented, it's just one layer deeper (`px auth login`):

<img width="818" alt="image" src="https://user-images.githubusercontent.com/66266496/159312621-b273fad3-a3d9-4fdc-b2d0-5de1ff3ee1ef.png">
