### ISSUE TITLE
pxl script execution error when 'select' includes req_body for http_events

### ISSUE THREAD

**Issue by jdix531** [pixie-io/pixie#416]
**Describe the bug**

The pxl script I have should execute for and return all fields, however, when req_body is included in select or if select is left out entirely (defaulting to all values per documentation) an exception occurs in the pxapi library. When select is explicit all values are able to be included except req_body.

**To Reproduce**
have this pxl script:
```
import px # type: ignore # pylint: disable=import-error 


def http_data(start_time: str, end_time: str):
    df = px.DataFrame(
        table='http_events',
        select=[
            'time_',
            'upid',
            'remote_addr',
            'remote_port',
            'trace_role',
            'major_version',
            'minor_version',
            'content_type',
            'req_headers',
            'req_method',
            'req_path',
            # 'req_body',
            'req_body_size',
            'resp_headers',
            'resp_status',
            'resp_message',
            'resp_body',
            'resp_body_size',
            'latency'
        ],
        start_time=start_time,
        end_time=end_time
    )

    df.namespace = df.ctx['namespace']
    df.node = df.ctx['node']
    df.svc = df.ctx['service']
    df.pod = df.ctx['pod']
    df = df.drop(columns=['upid'])

    return df

px.display(http_data(START_TIME,END_TIME), 'http_events') # type: ignore
```

call pxl script as such:
```
px_client = pxapi.Client(token=px_token)
clusters = px_client.list_healthy_clusters()
pixie_cluster_to_use = clusters[2]
px_conn = px_client.connect_to_cluster(cluster=pixie_cluster_to_use.id)

script = px_conn.prepare_script(time_segment_script)
# Add a callback function to the script
script.add_callback("http_events", update_logging_data)
# run the script which updates the global var for log data
script.run()
```

**Expected behavior**
The pxl script should complete successfully with all fields.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens.

![Screen Shot 2022-03-29 at 10 56 36 AM](https://user-images.githubusercontent.com/5290156/160643813-d68546f4-ca7f-4aec-a2a4-f949a39c4d80.png)

**Logs**

Please attach the logs by running the following command:
```
./px collect-logs
```

**App information (please complete the following information):**
- Pixie version
  - pxapi 0.4.1 python
- K8s cluster version
  - v1.19.15-eks-9c63c4
- Node Kernel version
  - currently unknown, working on access
- Browser version
  - N/A

I am using M1 mac fwiw. Installed with the following notes/flags:
brew install rust
export GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1
export GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1
export CFLAGS="-I /opt/homebrew/opt/openssl@1.1/include"
export LDFLAGS="-L /opt/homebrew/opt/openssl@1.1/lib"

**Additional context**

**Comment by philkuz** [comment]
Hi @jdix531 thanks for flagging this. 

I'm having trouble reproducing this locally, maybe you can help me out.

First I noticed that you're using Python 3.10.1 , correct? I wasn't able to install pxapi using 3.10 without some modifications to the deps. Do you know which grpcio and grpcio-tools versions you are using? 

Btw just tested and 3.8 definitely works if that's an option for you.

Second, are you completely sure the issue is related to req_body? We don't special case req_body. Are you able to get any results if you say include `req_body` but remove `resp_body`? Also is this something that intermittently happens or happens all the time?

**Comment by jdix531** [comment]
Hi @philkuz, I have tried python 3.8 with the same results. I've been on macos darwin. I tried emulating an x64 docker container (python:3.8.9) which installs just fine and without the below settings but has the same error.

Switching to an x64 machine running manjaro the error still occurs, however, I get what looks like some useful console output to go with the errors - this happens every time:

```
[libprotobuf ERROR google/protobuf/wire_format_lite.cc:577] String field 'px.api.vizierpb.StringColumn.data' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.
```

Perhaps I need to upgrade our pixie deployment? I see this as a 2018/9 issue for protobuf https://github.com/protocolbuffers/protobuf/issues/4691. Let me know what you think of this!

**Comment by jdix531** [comment]
Hi - some good news. I re-deployed pixie to this cluster and this error doesn't seem to occur anymore.

We have a separate issue (where pixie is crashing, recovering, but web-ui and api say the health checks are failing and it won't work) but that's a) a separate issue and b) I want to look more into it first before reaching out.

Closing for now, thanks for helping me look into this @philkuz.
