### ISSUE TITLE
Self Hosted Pixel Cloud on EKS.  Deployment fails with some pods entering CrashLoops

### ISSUE THREAD

**Issue by diegobes** [pixie-io/pixie#417]
**Describe the bug**
I follow the instructions to Self Host Pixie Cloud on my own EKS cluster described in: https://docs.px.dev/installing-pixie/install-guides/self-hosted-pixie/

Step 1.8 Was performed and during step 1.9 I see several PODs are in CrashLoops

**To Reproduce**
Perform the steps from : https://docs.px.dev/installing-pixie/install-guides/self-hosted-pixie/
At sep 1.9, several pods are in CrashLoops and they never recover

**Expected behavior**
After sometime, all the Pods should be in Running STATUS

**Screenshots**

NAME                   READY  STATUS       RESTARTS  AGE
api-server-766b687c4c-hfks2        1/1   Running      2     61m
**artifact-tracker-server-5bb4c7b4c-5xjf6  0/1   CrashLoopBackOff  17     61m**
auth-server-bbbb4f668-v824f        1/1   Running      1     61m
cloud-proxy-84d5499c9c-zcvng       2/2   Running      1     61m
config-manager-server-5f79ffcb96-fqxqn  1/1   Running      0     61m
create-admin-job-j799d          0/1   Completed     0     61m
create-hydra-client-job-v44zj       0/1   Completed     0     61m
cron-script-server-55f4bbb544-6rlgw    1/1   Running      1     61m
dnsmgr-server-6999c9dd8d-7hg7q      1/1   Running      1     61m
hydra-7cf59c49c6-97fd5          1/1   Running      0     61m
**indexer-server-66bb474b4b-7nzmr      0/1   CrashLoopBackOff  24     61m**
kratos-7c549b66f4-bgjtl          1/1   Running      0     61m
metrics-server-594946ff45-hmp4d      1/1   Running      0     61m
pl-elastic-es-data-0           1/1   Running      0     61m
pl-elastic-es-master-0          1/1   Running      0     61m
pl-elastic-es-master-1          1/1   Running      0     61m
pl-nats-0                 1/1   Running      0     61m
pl-nats-1                 1/1   Running      0     61m
pl-nats-2                 1/1   Running      0     61m
pl-stan-0                 1/1   Running      0     61m
pl-stan-1                 1/1   Running      0     59m
pl-stan-2                 1/1   Running      0     49m
plugin-server-589b769d6c-lx5hj      1/1   Running      1     61m
postgres-5cb4875b6d-8ghnx         1/1   Running      0     17m
profile-server-7b6bb665dd-4rgkt      1/1   Running      1     61m
project-manager-server-5ccfb7687-6nkmj  1/1   Running      1     61m
scriptmgr-server-68ccf967d4-lvk48     1/1   Running      1     61m
vzconn-server-67d9c6486f-v9wqr      1/1   Running      7     61m
**vzmgr-server-6c44d9bdf9-9c6tx       0/1   CrashLoopBackOff  9     24m**

**Logs**

```
**kubectl logs -n plc vzmgr-server-6c44d9bdf9-9c6tx**
level=fatal msg="Failed to apply migrations" func=main.main file="src/cloud/vzmgr/vzmgr_server.go:185" error="Dirty database version 11. Fix and force version." (edited) 
[2:25](https://pixie-community.slack.com/archives/CQ63KEVFY/p1648589100337839)

**kubectl logs -n plc artifact-tracker-server-5bb4c7b4c-5xjf6**
time="2022-03-29T21:22:31Z" level=fatal msg="Failed to apply migrations" func=main.mustLoadDB file="src/cloud/artifact_tracker/artifact_tracker_server.go:79" error="Dirty database version 1. Fix and force version."
```

**App information (please complete the following information):**
- Pixie version
git clone From Master

- K8s cluster version
EKS 1.21

- Node Kernel version
5.4.181-99.354.amzn2

**Comment by diegobes** [comment]
**Update**
I recreate the entire cluster, exactly the same configuration as before.
This time it works.

I cannot explain what is the difference, but it is not stable.

**Comment by zasgar** [comment]
@diegobes , we have not been able to reproduce this issue. It might be related to a bad migration or a bug that has already been fixed. Please reopen if you continue have issues with this.

**Comment by dontmint** [comment]
I still meet this issue today when following Self Hosted Pixie Cloud and issue #266 
Deployment - **vzmgr-server** 
```
level=info msg="Connected to Postgres"
level=fatal msg="Failed to apply migrations" error="Dirty database version 9. Fix and force version."
```
The same error appears at **profile-server** and **plugin-server**
![Screen Shot 2022-07-12 at 13 57 52](https://user-images.githubusercontent.com/34891994/178428110-08d736f0-065b-41cd-aab2-8d62aed85551.png)

**Comment by dontmint** [comment]
> I still meet this issue today when following Self Hosted Pixie Cloud and issue #266 Deployment - **vzmgr-server**
> 
> ```
> level=info msg="Connected to Postgres"
> level=fatal msg="Failed to apply migrations" error="Dirty database version 9. Fix and force version."
> ```
> 
> The same error appears at **profile-server** and **plugin-server** ![Screen Shot 2022-07-12 at 13 57 52](https://user-images.githubusercontent.com/34891994/178428110-08d736f0-065b-41cd-aab2-8d62aed85551.png)

I figured this out because the image version of PostgreSQL was set to 13.3 in the current template, other tools like  `plugin-db-updater-job` use the 14-alpine version. I think this was a miss-match version when the migrate script ran. The error is gone when I manually change the PostgreSQL to 14.4 and re-install everything.
