### ISSUE TITLE
Add back Cmd+K Command Pallete in the UI  for fast script search and execution

### ISSUE THREAD

**Issue by philkuz** [pixie-io/pixie#433]
**Is your feature request related to a problem? Please describe.**
I miss the old Pixie days where you could Cmd/ctrl +k and find a script. Makes the debugging process much faster. 
**Describe the solution you'd like**
Cmd/ ctrl + k opens up an Omni bar / Command Pallette view that you can then type in scripts and fuzzy match scripts. Can also add support for script arguments, but IMO that's a secondary feature to just having script access. 

**Describe alternatives you've considered**
Current action is to use the script drop down which requires a mouse. 
You could also try to use something like vimium to access click points in the UI - but that's quite clunky.
Maybe on the vimium route we could add some single letter actions that do something special in the UI. Has some risks that people will miss a text box, start typing and trigger a bunch of actions.

**Comment by NickLanam** [comment]
Resolved by #593 and a number of follow-ups since then.
