### ISSUE TITLE
Pixie CLI failing validation on K3s

### ISSUE THREAD

**Issue by bpschmitt** [pixie-io/pixie#442]
**Describe the bug**
I'm attempting to install Pixie into a K3s cluster and the cluster check fails stating that the cluster type is unsupported.  Looking at the Pixie docs, K3s is listed as [being supported](https://docs.px.dev/installing-pixie/requirements/#kubernetes-local-development-environments).

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6+k3s1", GitCommit:"418c3fa858b69b12b9cefbcff0526f666a6236b9", GitTreeState:"clean", BuildDate:"2022-04-28T22:16:18Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6+k3s1", GitCommit:"418c3fa858b69b12b9cefbcff0526f666a6236b9", GitTreeState:"clean", BuildDate:"2022-04-28T22:16:18Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```

```
Running Cluster Checks:
 ✔    Kernel version > 4.14.0 
 ✔    Cluster type is supported 
 ✔    K8s version > 1.16.0 
 ✔    Kubectl > 1.10.0 is present 
 ✔    User can create namespace 
 ✕    Cluster type is in list of known supported types  ERR: Cluster type is not in list of known supported cluster types. Please see: https://docs.px.dev/installing-pixie/requirements/
 ```
 
 Node Info:
 
 ```
 Linux kubernetes-vm 5.13.0-1024-gcp #29~20.04.1-Ubuntu SMP Thu Apr 14 23:15:00 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
 ```
 
 Installing Pixie into the same cluster using Helm works successfully.
 
**To Reproduce**
1. Build K3s cluster
2. Attempt Pixie deploy via CLI
3. Shed a single tear :( 

**Expected behavior**
I would expect Pixie to install without issues as K3s is listed as supported.

**Comment by htroisi** [comment]
The CLI is failing because k3s is missing from our `allowedClusterTypes` list: https://github.com/pixie-io/pixie/blob/main/src/pixie_cli/pkg/utils/checks.go#L68

As a temporary workaround, you can use `--check=false` when deploying Pixie:
```
px deploy --check=false
```

**Comment by htroisi** [comment]
The fix for this has landed, but won't be available until the next CLI release.
