### ISSUE TITLE
How deploy vizier components with changes in daemonsets (hostPath changes)

### ISSUE THREAD

**Issue by arnikasky** [pixie-io/pixie#443]
**Is your feature request related to a problem? Please describe.**
We need a description of how we can deploy vizier with custom changes in components.

**Describe the solution you'd like**
I want have documentation of how we can deploy vizier with custom changes in components.

**Describe alternatives you've considered**
-

**Additional context**
My main question is: how can I deploy vizier components with changes in daemonsets (I need change hostPath due to security checks, which are implemented in my cluster).

Sorry, if it's wrong type of issue, please feel free to change it.

**Comment by htroisi** [comment]
Answer from @aimichelle via Pixie's [Community Slack](https://slackin.px.dev/):

> If you are [deploying Pixie using the CLI](https://docs.px.dev/installing-pixie/install-schemes/cli/#2.-deploy-pixie), you can use the `patches` flag which behaves like patching in `kubectl`:
> ```
> px deploy --patches='vizier-pem:{"spec":{"template":{"spec":{"volumes":[{"name":"sys","hostPath": {"path":"/var/log/sys","type":"Directory"}}]}}}}'             
> ```
