### ISSUE TITLE
Negative numbers hang Pixie UI max_num_records

### ISSUE THREAD

**Issue by vikranth22446** [pixie-io/pixie#448]
**Describe the bug**
Using negative numbers on the Pixie UI max_num_records field causes the system to hang.

**To Reproduce**
1. Open Pixie UI
2. Type a negative number(ex. -100) on the max_num_records
3. Watch UI hang

**Expected behavior**
It's expected to return 0 records

**Screenshots**
<img width="1837" alt="Screen Shot 2022-06-01 at 3 13 21 PM" src="https://user-images.githubusercontent.com/10752522/171510627-48d92daf-b9d0-4740-a34e-cbc893f15025.png">

**Logs**
[pixie_logs_20220601150922.zip](https://github.com/pixie-io/pixie/files/8819067/pixie_logs_20220601150922.zip)

**App information (please
 complete the following information):**
- Pixie version: 0.7.10+Distribution.fb7da3f.20220531183919.1
- K8s cluster version: 1.21
- Node Kernel version: 5.4.0-1066-gke 
- Browser version: Version 101.0.4951.64 (Official Build) (x86_64)

**Comment by zasgar** [comment]
@aimichelle , not sure if this is UI or backend related. Based on that we should set the priority appropriately.
