### ISSUE TITLE
Provide pod labels with metadata

### ISSUE THREAD

**Issue by tharinduwijewardane** [pixie-io/pixie#449]
**Is your feature request related to a problem? Please describe.**
We are unable to aggregate telemetry data using a ID we set as a pod label.

**Describe the solution you'd like**
Provide pod labels (as a string?) along with [the existing metadata](https://docs.pixielabs.ai/reference/pxl/operators/dataframe.ctx.__getitem__/)
Often a pod name is a generated string and the users track pods by setting labels. Therefore this is a useful feature to have.

**Describe alternatives you've considered**

**Additional context**

**Comment by tharinduwijewardane** [comment]
What is the feasibility of this? Can someone please point to the existing code where pod ids and pod names are extracted.

**Comment by zasgar** [comment]
@tharinduwijewardane, This will be a great feature for us to have. Are you interested in contributing this? We can help out as needed.

**Comment by tharinduwijewardane** [comment]
@zasgar Yes. I had difficulties building pixie locally (asked them in pixienaut channel). Finally I could get it working with ubuntu 22.04. I am going to look into this now.

**Comment by tharinduwijewardane** [comment]
@aimichelle @zasgar I submitted a PR for this. Could you please review.
