### ISSUE TITLE
Allow custom registry path for container images

### ISSUE THREAD

**Issue by maxlemieux** [pixie-io/pixie#473]
**Is your feature request related to a problem? Please describe.**
Installing to air gapped  environments or clusters which use private container registries, is currently complicated by the lack of a configuration setting for Docker container registry path.

Since many Pixie resources are pulled in via operator, and don't have a presence in the installation manifest, users can't currently point to their custom registries for these resources. Example: Job resource in px-operator namespace: once installed, the image path is immutable for the pod resource: `Image: gcr.io/pixie-oss/pixie-prod/operator/bundle:0.0.26`

**Describe the solution you'd like**
A chart setting for the Pixie operator chart which allows specifying the registry path.

**Describe alternatives you've considered**

- The process for pre-pulling images to nodes varies by environment and is complex to maintain.
- Updating affected resources after installation - immutability makes this a challenge

**Comment by aimichelle** [comment]
Changes are in: https://github.com/pixie-io/pixie/commit/a065a1ea833beb8c04e96a23fc81bcd9bedb243b https://github.com/pixie-io/pixie/commit/929f7ca32f3e950c62cc140418a52b1f1abb857e https://github.com/pixie-io/pixie/commit/f8db8369f004f3ba990510bb2c6006e692cc836d https://github.com/pixie-io/pixie/commit/4e4a4205dbe9ca0eb0a1b6b7f709be7f2ce80b2c https://github.com/pixie-io/pixie/commit/e84f6c1eaf2d1951f2130863a1e8566ad28017ce

These changes will be included in the cloud, vizier, operator, and CLI releases next week, along with docs (see https://github.com/pixie-io/docs.px.dev/pull/228) .
