### ISSUE TITLE
Error when DeployingVizier

### ISSUE THREAD

**Issue by yinleixu** [pixie-io/pixie#474]
![error](https://user-images.githubusercontent.com/30719410/177041193-2ca58a92-cff6-4ded-b108-be4ff01d5c92.png)
[nodes.log](https://github.com/pixie-io/pixie/files/9034818/nodes.log)

the server.log is empty

**Comment by aimichelle** [comment]
Hello @yinleixu ! Sorry to hear you're running into this issue. 
I just tried reproducing by deploying a self-hosted cloud + vizier off of main, but was unable to. Can you confirm which commit hash you are building off of, and versions you are running for the CLI and Pixie operator? 
For CLI: `px version`
And for operator version: `kubectl get pods -n px-operator` `kubectl describe pod vizier-operator-<hash> -n px-operator` and get the version from the image tag.

**Comment by yinleixu** [comment]
Thank you for your reply，I have some image pull err. I can't pull the image from gcr.io,but i have load it to environment.
I want set  all yaml file  imagePullPolicy: Never,  where i can set it apply for all when px deploying.
![1657026702862](https://user-images.githubusercontent.com/30719410/177335729-e8801b1b-e703-4a52-a9f7-a5206fd24ad6.png)

**Comment by yinleixu** [comment]
hi:
The fllow infomation as you want to see.
![1657094947871](https://user-images.githubusercontent.com/30719410/177502186-55ac4a15-e304-4827-b13d-7ec1ae8be465.png)

[root@master ~]# kubectl get pods -A
NAMESPACE        NAME                                       READY   STATUS             RESTARTS   AGE
default          recycler-for-pv2                           0/1     Completed          0          3d3h
default          recycler-for-pv3                           0/1     Completed          0          3d3h
default          recycler-for-pv4                           0/1     Completed          0          3d6h
default          recycler-for-pv6                           0/1     Completed          0          3d3h
elastic-system   elastic-operator-0                         1/1     Running            4          3d3h
kube-system      coredns-7ff77c879f-nfg4z                   1/1     Running            12         5d16h
kube-system      coredns-7ff77c879f-vsks7                   1/1     Running            12         5d16h
kube-system      etcd-master                                1/1     Running            12         5d16h
kube-system      kube-apiserver-master                      1/1     Running            12         5d16h
kube-system      kube-controller-manager-master             1/1     Running            12         5d16h
kube-system      kube-flannel-ds-jvnh5                      1/1     Running            14         5d16h
kube-system      kube-flannel-ds-mzpq4                      1/1     Running            13         5d16h
kube-system      kube-flannel-ds-p69bz                      1/1     Running            12         5d16h
kube-system      kube-proxy-8bpbf                           1/1     Running            13         5d16h
kube-system      kube-proxy-g7bcj                           1/1     Running            11         5d16h
kube-system      kube-proxy-jmx55                           1/1     Running            11         5d16h
kube-system      kube-scheduler-master                      1/1     Running            13         5d16h
olm              catalog-operator-5b484889dc-8gmjd          1/1     Running            2          3d2h
olm              olm-operator-69c5ff9b78-c5r9m              1/1     Running            2          3d2h
plc              api-server-6887c5b47d-5fbjk                1/1     Running            5          3d3h
plc              artifact-tracker-server-76d458b88b-rch9r   1/1     Running            3          3d3h
plc              auth-server-5dc9f5c65b-8r7gn               1/1     Running            2          3d3h
plc              cloud-proxy-566f877d5f-wjj9h               2/2     Running            7          3d3h
plc              config-manager-server-594b8f6897-5hlsf     1/1     Running            2          3d3h
plc              create-admin-job-gkx4s                     0/1     Completed          0          3d3h
plc              create-hydra-client-job-tbf68              0/1     Completed          0          3d3h
plc              cron-script-server-7d4648b6f7-dpnz7        1/1     Running            4          3d3h
plc              hydra-f96594bf9-fdnww                      1/1     Running            2          3d3h
plc              indexer-server-5f8d78f599-48n72            1/1     Running            9          3d3h
plc              kratos-69d8886679-tr7fw                    1/1     Running            2          3d3h
plc              metrics-server-5688cfb4d7-4sq4t            1/1     Running            4          3d3h
plc              pl-elastic-es-data-0                       1/1     Running            2          3d3h
plc              pl-elastic-es-master-0                     1/1     Running            2          3d3h
plc              pl-elastic-es-master-1                     1/1     Running            2          3d3h
plc              pl-nats-0                                  1/1     Running            2          3d3h
plc              pl-nats-1                                  1/1     Running            2          3d3h
plc              pl-nats-2                                  1/1     Running            2          3d3h
plc              pl-stan-0                                  1/1     Running            8          3d3h
plc              pl-stan-1                                  1/1     Running            4          3d3h
plc              pl-stan-2                                  1/1     Running            5          3d2h
plc              plugin-db-updater-job-557g7                0/1     Completed          0          3d3h
plc              plugin-server-669d97f4d9-hrgw2             1/1     Running            2          3d3h
plc              postgres-595fcfb445-2zh2v                  1/1     Running            2          3d3h
plc              profile-server-55bbcb8d98-h4d4k            1/1     Running            4          3d3h
plc              project-manager-server-754945d48c-lgq22    1/1     Running            3          3d3h
plc              scriptmgr-server-7d9b79c8f8-rdj9j          1/1     Running            3          3d3h
plc              vzconn-server-5bb79b5979-g4hcl             1/1     Running            9          3d3h
plc              vzmgr-server-db5799d8-6d5mm                1/1     Running            9          3d3h
px-operator      pixie-operator-index-6ghfs                 0/1     ImagePullBackOff   0          19h
px-operator      pixie-operator-index-qlkfj                 0/1     ImagePullBackOff   0          19h

**The pod of plc has  ImagePullBackOff   too . I modify the file  /root/pixie/k8s/cloud/base/ *deployment.yaml like 
![1657095191034](https://user-images.githubusercontent.com/30719410/177503084-767e803c-d77d-4ef9-bb8a-ca5c35823c38.png)

**Comment by aimichelle** [comment]
Got it, we just added some deploy instructions for airgapped environments in https://github.com/pixie-io/pixie/issues/266 (see most recent post). 
This should help resolve the ImagePull issues that you have been seeing.

I will close out this issue in favor of that one--please let us know there if it works/doesn't work for you. Thanks!
