### ISSUE TITLE
Add Pixie UI support for script bundle env var

### ISSUE THREAD

**Issue by htroisi** [pixie-io/pixie#485]
**Problem**
When [installing Pixie in an air gap environment ](https://github.com/pixie-io/pixie/issues/266#issuecomment-1176767126), the Pixie UI will fail to load, unless you set up the script dev environment:
![image](https://user-images.githubusercontent.com/66266496/178346154-26800cb7-2eb3-40fb-af38-c01d73286407.png)

**Feature request**
The UI should honor an env variable at build time to point somewhere else for the bundle. The UI should also provide a more useful error message when it fails to load a bundle.

**Comment by NickLanam** [comment]
Done in [this commit](https://github.com/pixie-io/pixie/commit/c2ae6d8041ef41e72244af9ed21aa6925a3b9581).

Here's what changed:

- Two new env vars, in `script_bundles_config.yaml` for each environment in `k8s/cloud/*`:
  - `SCRIPT_BUNDLE_URLS`: A JSON-stringified array of URL strings. Defaults to the OSS bundle.
    Pixie's UI tries to load a JSON document from each URL in this array. User can override, see below.

  - `SCRIPT_BUNDLE_DEV`: A JSON-stringified boolean. Defaults to `"false"`.
    If `"true"`, bundles are queried with a cache-busting timestamp parameter to make [script development](https://docs.px.dev/tutorials/pxl-scripts/script-dev-environment/) a bit easier.
    The instructions as-is still work, it's only the defaults that work differently.

- There's a new `localStorage` key, `px-custom-script-bundle-paths`.
  - If set, it replaces the value of `SCRIPT_BUNDLE_URLS` and forces `SCRIPT_BUNDLE_DEV` on.
  - If it isn't set, the old `localStorage` keys are checked like before.

- If Pixie's UI fails to load a script bundle, it now shows an error view linking to these instructions.

**Comment by htroisi** [comment]
@NickLanam I ran into the new UI error when following the self-hosted [install guide](https://docs.px.dev/installing-pixie/install-guides/self-hosted-pixie/) using a minikube test cluster. 
<img width="667" alt="Screen Shot 2022-08-18 at 1 51 58 PM" src="https://user-images.githubusercontent.com/66266496/185492573-306fa6c0-c373-45c1-a352-6ad7b1625788.png">

I was using the default yamls (I didn't change `SCRIPT_BUNDLE_URLS` or `SCRIPT_BUNDLE_DEV`), so I wasn't expecting to see this error. 

It looks `isDev` is getting set to true in [script-bundle.tsx](https://github.com/pixie-io/pixie/blob/main/src/ui/src/utils/script-bundle.tsx#L140), given that I get the `SCRIPT_BUNDLES_OVERRIDDEN` error. Yet, `pl-script-bundles-config` shows 
```
Name:         pl-script-bundles-config
Namespace:    plc
Labels:       app=pl-cloud
Annotations:  <none>

Data
====
SCRIPT_BUNDLE_DEV:
----
false
SCRIPT_BUNDLE_URLS:
----
[ "https://storage.googleapis.com/pixie-prod-artifacts/script-bundles/bundle-oss.json" ]

BinaryData
====

Events:  <none>
```

**Comment by htroisi** [comment]
Closing this because I have not been able to reproduce this bug.
