### ISSUE TITLE
Add air gap artifact bundle to release process

### ISSUE THREAD

**Issue by htroisi** [pixie-io/pixie#486]
**Problem**
[Installing Pixie in an air gap environment](https://github.com/pixie-io/pixie/issues/266#issuecomment-1176767126), requires many manual steps including creating a list of required images (for Cloud and Vizier) and using `kustomize` to create several Kubernetes manifests. These steps are universal to all air gap installations.

**Feature request**
Add an air gap artifact bundle that is automatically created during a release. This bundle should include: 
- `pixie-cloud-images.txt`: a list of the images required to deploy Pixie Cloud:
```
filename=pixie-image-list.txt
kustomize build "k8s/cloud_deps/public/" |  yq e '.. | .image? | select(.)' -o=json - | jq 'strings' | sort | uniq > ${filename}
kustomize build "k8s/cloud/public/" |  yq e '.. | .image? | select(.)' -o=json - | jq 'strings' | sort | uniq >> ${filename}
kustomize build "k8s/cloud_deps/base/elastic/operator" |  yq e '.. | .image? | select(.)' -o=json - | jq 'strings' | sort | uniq >> ${filename}
```
- `px_cloud.yaml`, which merges the following yaml files (I believe these can all be deployed in parallel): 
```
kustomize build k8s/cloud_deps/base/elastic/operator > px_operator.yaml
kustomize build k8s/cloud_deps/public > px_cloud_deps.yaml
kustomize build k8s/cloud/public/ > px_cloud.yaml
```
- `vizier_secrets.yaml`: this is already available at the following path: 
```
https://storage.googleapis.com/pixie-dev-public/vizier/vizier_secrets.yaml
```
- The vizier yaml files already available at the following path:
```
https://storage.googleapis.com/pixie-dev-public/vizier/0.11.5/vizier_yamls.tar
```
- `pixie-vizier-images.txt`: a list of the images required to deploy Pixie Vizier (without etcd):
```
filename=pixie-vizier-images.txt
curl https://storage.googleapis.com/pixie-dev-public/vizier/0.11.5/vizier_yamls.tar | tar xj
cat ~/Downloads/yamls/vizier_deps/nats_prod.yaml |  yq e '.. | .image? | select(.)' -o=json - | jq 'strings' | sort | uniq > ${filename}
cat ~/Downloads/yamls/vizier/vizier_metadata_persist_prod.yaml |  yq e '.. | .image? | select(.)' -o=json - | jq 'strings' | sort | uniq >> ${filename}
```
- `pixie-vizier-images-etcd.txt`: a list of the images required to deploy Pixie Vizier (with etcd):
```
filename=pixie-vizier-images-etcd.txt
curl https://storage.googleapis.com/pixie-dev-public/vizier/0.11.5/vizier_yamls.tar | tar xj
cat ~/Downloads/yamls/vizier_deps/etcd_prod.yaml |  yq e '.. | .image? | select(.)' -o=json - | jq 'strings' | sort | uniq > ${filename}
cat ~/Downloads/yamls/vizier/vizier_etcd_metadata_prod.yaml |  yq e '.. | .image? | select(.)' -o=json - | jq 'strings' | sort | uniq >> ${filename}
```
- `bundle-oss.json`: script bundle as required by https://github.com/pixie-io/pixie/issues/485

**Comment by aimichelle** [comment]
Completed as a part of https://github.com/pixie-io/pixie/commit/6a7e873a57ac85bfbf79e4afc0d44691e52d68c1 and https://github.com/pixie-io/pixie/commit/9ef2e4793568fd77891ec25867b3adcd9fb09d4c.
