### ISSUE TITLE
replace the mirror   px-operator job image

### ISSUE THREAD

**Issue by dafu-wu** [pixie-io/pixie#543]
when i execute the command ：px deploy --dev_cloud_namespace plc
      ...
      px-operator      d1ac3a93a16150c9cbd3d287f228e73fa3f72c7d674193868e18363740pgmks   0/1     Init:ImagePullBackOff   0        
      ...
      ...
      image: gcr.io/pixie-oss/pixie-prod/operator/bundle:0.0.30
      imagePullPolicy: Always
      ...
      I can't pull down the mirror for some reason, I want to replace the mirror. what shoud i do? please help me，thanks.

**Comment by dafu-wu** [comment]
use ./ci/operator_helm_build_release.sh script to solve the problem.

**Comment by flyme001** [comment]
/ci/operator_helm_build_release.sh 如何替换versions_file ="$(realpath "${VERSIONS_FILE:?}")" ？ versions_file如何定义
