### ISSUE TITLE
Python package pins the `pip` utility

### ISSUE THREAD

**Issue by Lawouach** [pixie-io/pixie#548]
**Describe the bug**

Currently, the Python api package pins the `pip` utility in its requirements:

https://github.com/pixie-io/pixie/blob/a20c2ec5d46ff715f99ecb25613618386e923b25/src/api/python/requirements.txt#L7

This is not really convenient as `pip` is often updated and kept to its latest version. Distributing anything relying pixie will create some friction.

**Expected behavior**

Maybe you can be more forgiving and pin to the major version only?

```
pip~=22.0
```

**Comment by Lawouach** [comment]
Looking at the code, `pip` seems to only be used to package the distribution, not in the actual code. Can we remove that dependency altogether?

**Comment by htroisi** [comment]
@Lawouach I don't think we need to pin pip. This was probably added accidentally when we froze the requirements. 

Would you be willing to submit a PR? Feel free to review the other requirements too. Thanks!
