### ISSUE TITLE
Release a new reversion of the Python client

### ISSUE THREAD

**Issue by Lawouach** [pixie-io/pixie#563]
**Is your feature request related to a problem? Please describe.**

Following #548, would it be possible to release the Python package again please?
I'm tryiong to release my [Chaos Toolkit extension](https://github.com/chaostoolkit-incubator/chaostoolkit-pixie) for it, and it fails with Python 3.10 because of the dependencies.

I can't directly pip install this repository either because the code is not at the top level as regular Python packages.

Thanks.

**Comment by philkuz** [comment]
Hey @Lawouach I just released 0.6.0: https://pypi.org/project/pxapi/. Let me know if you have any issues. I tried out the chaos toolkit and it seemed to work for me on Python 3.10.4 w/ pxapi==0.6.0

By the way, thanks for your feedback on the Pixie Python API. Glad to see that Pixie can be useful for you!

**Comment by Lawouach** [comment]
Thanks!

Happy to. I was integrating Pixie with the [Chaos Toolkit](https://chaostoolkit.org/drivers/pixie/).
