### ISSUE TITLE
pixie cloud install in k8s but not minikube

### ISSUE THREAD

**Issue by 1006er** [pixie-io/pixie#565]
**Describe the bug**
I tried to install pixie in self-host mode on the real k8s not minikube. When installing pixie cloud, I followed the documentation to set DNS. After running dev_dns_updater.go, the browser still cannot resolve the domain name and cannot be accessed through dev.withpixie.dev. And I would like to know if the installation method of pixie cloud shown in the documentation is only valid for minikube?
**Expected behavior**
The browser can access the pixie cloud service through dev.withpixie.dev and set the password of pixie cloud.

**App information (please complete the following information):**
- Pixie version
- K8s cluster version: 1.12.1
- Node Kernel version: 5.4.0
- Browser version:  104.0.5112.79 (Official Build) (64-bit)

**Comment by philkuz** [comment]
I use dev_dns_updator on GKE and k0s before and it worked fine. Are you sure you're running dev_dns_updater in the right place? 

The TLDR of dev_dns_updater is that it adds an entry into `/etc/hosts` which is read during DNS resolution. Are you possibly running dev_dns_updater in a VM and the browser outside the VM?

**Comment by 1006er** [comment]
> I use dev_dns_updator on GKE and k0s before and it worked fine. Are you sure you're running dev_dns_updater in the right place?
> 
> The TLDR of dev_dns_updater is that it adds an entry into `/etc/hosts` which is read during DNS resolution. Are you possibly running dev_dns_updater in a VM and the browser outside the VM?

Hi, thanks for your reply. 
I run the dev_dns_updater in the vm, but it doesn't seem to change the vm's /etc/hosts file, and the dev.withpixie.dev cannot be accessed through the browser in the vm.

I tried to manually add the /ect/hosts file on the master node and bind the external IP of cloud-proxy-service and vzconn-service to the domain name.
```
192.168.253.157     dev.withpixie.dev work.dev.withpixie.dev segment.dev.withpixie.dev docs.dev.withpixie.dev
192.168.253.157     cloud.dev.withpixie.dev
```
Through this, I can access pixie cloud through the domain name and set a password.
But when using the yaml file to install Pixie Platform. An error occurred.
```
time="2022-08-04T07:35:39Z" level=error msg="Failed to get latest vizier version" error="rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup dev.withpixie.dev on 10.96.0.10:53: no such host""
```
It also seems to be related to the resolution of the domain name.

I would like to know if dev_dns_updater only adds entities to /etc/hosts on the master node, or if it is added for all nodes.

**Comment by philkuz** [comment]
Ah I think I have an idea what's going wrong, currently running through the verification process right now. You're talking about this YAML deployment option: https://docs.px.dev/installing-pixie/install-schemes/yaml/#4.-extract-manifests right?

That process is for a cloud that has a properly setup DNS configuration, community cloud being one such example. You'll probably need to add the `--dev_cloud_namespace plc` argument to your `px deploy` command that creates the yamls. If you can, I would just go with the `px deploy` directions listed here to ensure that your self-hosted install works: https://docs.px.dev/installing-pixie/install-guides/self-hosted-pixie/#3.-deploy-pixie

**Comment by philkuz** [comment]
Update: was able to repro your problem. The fix is to specify dev_cloud_namespace:
```
px deploy --extract_yaml ./ --deploy_key=$PX_DEPLOY_KEY --dev_cloud_namespace plc
```

**Comment by philkuz** [comment]
Note you'll have to do the workaround in #571 when you are re-deploying
