### ISSUE TITLE
Add "copy" button to data tables

### ISSUE THREAD

**Issue by aimichelle** [pixie-io/pixie#581]
**Is your feature request related to a problem? Please describe.**
When sharing data to users (especially debug information, such as _DebugMDState), it's useful to copy and paste the data directly from the data tables in the UI. In some cases where the output is especially long, this process can be particularly annoying.

**Describe the solution you'd like**
It would be nice to have a button in the data table which allows you to copy the contents of the row to clipboard.

**Comment by divaspathak** [comment]
Hello there, can I work on this issue? Can you give me more info regarding this?

**Comment by aimichelle** [comment]
Hello @divaspathak , just checking in! Have you made any progress here? Happy to give pointers if you need any.

**Comment by SakshiT25** [comment]
Hello @aimichelle, I would like to work on this issue, can you guide me through the process?

**Comment by shardulsr** [comment]
@aimichelle I would like to work on this issue, could you please assign it to me.

**Comment by shardulsrivastava** [comment]
@aimichelle was wondering if this issue is available, I can work on this
