### ISSUE TITLE
Add UI developer environment setup to DEVELOPMENT.md

### ISSUE THREAD

**Issue by htroisi** [pixie-io/pixie#587]
**Describe the Task**
For developers who want to work on Pixie's UI code, we should share instructions for setting up the development environment in [DEVELOPMENT.md](https://github.com/pixie-io/pixie/blob/main/DEVELOPMENT.md).

**Comment by zasgar** [comment]
@aimichelle , Can we just add a pointer to the src/ui/README.md file?
