### ISSUE TITLE
server_names_hash_bucket_size too low

### ISSUE THREAD

**Issue by Sindvero** [pixie-io/pixie#590]
**Describe the bug**
When deploying self-hosted pixie and if you set a very long domain name, you get the following error in the cloud-proxy-server container:

```
[emerg] 8#8: could not build server_names_hash, you should increase server_names_hash_bucket_size: 64
nginx: [emerg] could not build server_names_hash, you should increase server_names_hash_bucket_size: 64
```

**To Reproduce**
Set PL_DOMAIN_NAME to a very long domain name (e.g. very.very.long.domain.name.used.in.this.example.org) and see cloud-proxy-server container crash.

**Expected behavior**
It doesn't crash

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens.

**Logs**
[emerg] 8#8: could not build server_names_hash, you should increase server_names_hash_bucket_size: 64
nginx: [emerg] could not build server_names_hash, you should increase server_names_hash_bucket_size: 64

**Additional context**
I tried to set the env var SERVER_NAMES_HASH_BUCKET_SIZE to 128, but the env var didn't get apply to nginx.

**Comment by Sindvero** [comment]
The workaround is to add this line "server_names_hash_bucket_size 128;" to the http context of the nginx.conf file then mount it to the cloud proxy pod. 

But what do you think about having it directly to the file, like that people using long domain name won't have to workaround like that, I can PR the changes if you want? or create a new file just for it and include it in the nginx config?

**Comment by htroisi** [comment]
@Sindvero - thanks for reporting back with the solution. We'd be happy to accept a PR with this modification!

**Comment by Sindvero** [comment]
@htroisi - Here's the PR #596

**Comment by zasgar** [comment]
Thanks for the contribution @Sindvero!

**Comment by zasgar** [comment]
Thanks for identifying the fix. Can you make a PR it?
