### ISSUE TITLE
Upgrade Kratos to `v0.9.9+`

### ISSUE THREAD

**Issue by htroisi** [pixie-io/pixie#614]
**Is your feature request related to a problem? Please describe.**
I don't want to have to manually [set the admin account password](https://docs.px.dev/installing-pixie/install-guides/self-hosted-pixie/#1.-deploy-pixie-cloud-authentication-using-kratos-hydra) when installing Pixie Cloud. This manual step complicates installing Pixie using a GitOps processes (see [Slack thread](https://pixie-community.slack.com/archives/CQ63KEVFY/p1661821503468729)).

**Describe the solution you'd like**
Pixie uses Kratos `v0.5.4-alpha.1`. Upgrade to `v0.9.9+`. Once Kratos is upgraded, we can use the new Kratos feature which allows us to [import user credentials](https://www.ory.sh/docs/kratos/manage-identities/import-user-accounts-identities#importing-credentials). 

**Context**
There are a LOT of [breaking UI changes](https://github.com/ory/kratos/blob/master/CHANGELOG.md#breaking-changes-8) that need to be addressed. I attempted to upgrade this, but it was not simple.

**Comment by philkuz** [comment]
We are now using Kratos 0.10.1
