### ISSUE TITLE
PxL Compiler Optimization: Drop filters using px.contains() with empty strings

### ISSUE THREAD

**Issue by philkuz** [pixie-io/pixie#618]
**Is your feature request related to a problem? Please describe.**
While debugging performance issues in queries, I found that filters that use `px.contains()` with empty string arguments were very expensive but didn't do anything. `df = df[px.contains(df.pod, "")]` is equivalent to no filter.

This shows up with `px/perf_flamegraph` when no arguments are specified and on a 30-node cluster the explain looks like this:
<img width="732" alt="image" src="https://user-images.githubusercontent.com/5456019/195218253-392bdb76-fd9f-4017-920c-bd4061f46047.png">

**Describe the solution you'd like**
Optimization that drops filters where contain has an empty string as the second argument.

**Comment by shardulsrivastava** [comment]
Hello @philkuz, I want to work on this issue. Can you please assign it to me?

**Comment by shardulsrivastava** [comment]
@philkuz I am new to pixie, would definitely appreciate some guidance and pointers.

**Comment by philkuz** [comment]
You'll probably want to implement an optimization inside of the compiler.
You'll want to make sure your diff has the following:
1. A new optimization rule that removes filters from the graph
2. A unit test for that rule 
3. Ensure that you add the rule to the other optimizations.

Look at the Prune rule for some guidance: 
Rule: https://github.com/pixie-io/pixie/blob/main/src/carnot/planner/compiler/optimizer/prune_unconnected_operators_rule.cc
Test: https://github.com/pixie-io/pixie/blob/main/src/carnot/planner/compiler/optimizer/prune_unconnected_operators_rule_test.cc
Hope this helps!

**Comment by philkuz** [comment]
Hi @shardulsrivastava have you had a chance to try this out?

**Comment by shardulsrivastava** [comment]
@philkuz i have a hard time setting up the environment locally, I am using Mac, and instructions [here](https://github.com/pixie-io/pixie/blob/main/DEVELOPMENT.md) are not very specific to the compiler.

Could you please give some pointers.
