### ISSUE TITLE
How SBOM is generated

### ISSUE THREAD

**Issue by OrlinVasilev** [pixie-io/pixie#621]
Hi team,

looking for solutions how did you implement the SBOM creation!
Thank you!
Orlix

**Comment by JamesMBartlett** [comment]
If you look in `tools/licenses`, that contains the code to build the SBOM. 

There's a README file in there you can checkout. The short version of how it works is we attempt to pull licenses from github's API, and for dependencies for which that doesn't work, we have `manual_licenses.json` that we keep up to date.
