### ISSUE TITLE
Unable to change the postgres db password

### ISSUE THREAD

**Issue by tharinduwijewardane** [pixie-io/pixie#625]
**Describe the bug**
Unable to change the postgres username or password

https://github.com/pixie-io/pixie/blob/release/vizier/v0.12.6/scripts/create_cloud_secrets.sh#L39

**To Reproduce**
Change the POSTGRES_PASSWORD in create_cloud_secrets.sh
Follow steps to deploy pixie cloud (self host)

**Outcome**
Cloud pods crash with errors specifying inability to connect to postgres db

**App information (please complete the following information):**
- Pixie version: release/vizier/v0.12.6 (latest)

I identified the issue. Will send a PR

**Comment by philkuz** [comment]
@vihangm good to close this issue?
