### ISSUE TITLE
Malformed DNS response body

### ISSUE THREAD

**Issue by MrSupiri** [pixie-io/pixie#652]
**Describe the bug**
Response body of the records from `px/dns_data` script comes with malformed IP address. This is most likely occurs due to pointer misalignment when reading from the data buffer.  

**To Reproduce**
1. Open `px/dns_data` script from the Pixie console.
2. Finding a DNS query which has a `resp_body`
3. Inspect the `resp_body` of DNS query.

**Screenshots**
<img height="500px" src="https://user-images.githubusercontent.com/29277992/202086613-1aad221e-2308-4aff-a94e-08695092b6c7.png" />

**App information:**
- Pixie version: 0.12.2 (we are using an air gapped deployment) 
- K8s cluster version: v1.23.12
- Node Kernel version: AKSUbuntu-1804gen2containerd-2022.09.13 (5.4.0-1091-azure)

**Comment by oazizi000** [comment]
Issue appears to be related to a rapidjson string reference, for which the underlying data is moved. Fix coming soon.
