### ISSUE TITLE
Helm fails to render `pixie-operator-chart` templates. Failure during installing  `pixie-operator-chart` with ArgoCD due to `lookup` helm function

### ISSUE THREAD

**Issue by sturman** [pixie-io/pixie#658]
**Describe the bug**
Helm fails to render templates for 'pixie-operator/pixie-operator-chart' chart.

```
helm template pixie-operator pixie-operator/pixie-operator-chart --debug
install.go:192: [debug] Original chart version: ""
install.go:209: [debug] CHART PATH: /Users/user/Library/Caches/helm/repository/pixie-operator-chart-0.0.33.tgz


Error: execution error at (pixie-operator-chart/templates/00_olm.yaml:3:28): CRDs missing! Please deploy CRDs from https://github.com/pixie-io/pixie/tree/main/k8s/operator/helm/crds to continue with deploy.
helm.go:84: [debug] execution error at (pixie-operator-chart/templates/00_olm.yaml:3:28): CRDs missing! Please deploy CRDs from https://github.com/pixie-io/pixie/tree/main/k8s/operator/helm/crds to continue with deploy.
```

**To Reproduce**

1. Run `helm repo add pixie-operator https://pixie-operator-charts.storage.googleapis.com`
1. Run `helm template pixie-operator pixie-operator/pixie-operator-chart`

**Expected behavior**
Templates (Namespace, ClusterRole, ClusterRoleBinding, Deployment etc) should be rendered

**App information (please complete the following information):**
- Helm version: version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.19.3"}
- Helm chart: pixie-operator-chart
- Helm chart version: 0.0.33
- K8s cluster version: 1.22
- ArgoCD: v2.5.2+148d8da

**Additional context**
Most likely after commit https://github.com/pixie-io/pixie/commit/762396107c50ec875b6774f7ddd51cd5ba16f7f1 was pushed and released, the [helm function](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function) `lookup` is invoked in order to check if k8s cluster has "operators.coreos.com/v1" "OperatorGroup" resources. When running `helm template` the lookup is not supported.

```
Keep in mind that Helm is not supposed to contact the Kubernetes API Server during a helm template or a helm install|update|delete|rollback --dry-run, so the lookup function will return an empty list (i.e. dict) in such a case.
```
When trying to install `pixie-operator-chart` with ArgoCD it fails because ArgoCD executes `helm template` before installing the chart. So it makes impossible install chart `pixie-operator-chart` or `nri-bundle` https://github.com/newrelic/helm-charts/tree/master/charts/nri-bundle with ArgoCD 

The ArgoCD issue that could be related to this https://github.com/argoproj/argo-cd/issues/5202
Similar issue #421  was already reported

Anyway, the helm fails to template the chart `pixie-operator-chart` locally.

**Comment by zaljic** [comment]
I have the same issue
