### ISSUE TITLE
qb_wait container generating huge amount of logs

### ISSUE THREAD

**Issue by anjuls** [pixie-io/pixie#659]
I am actually shocked 🤕 to see an excessive log bill for the logs emitted by the qb_wait container in Pixie. 

- need to have JSON as default
- need to reduce unnecessary emits on STDERR

![image](https://user-images.githubusercontent.com/252614/203420047-9c9158ad-f3fb-4725-9b63-72d3a9037b65.png)

**Comment by aimichelle** [comment]
Looks like the same issue as https://github.com/pixie-io/pixie/issues/1596.
This will be fixed by https://github.com/pixie-io/pixie/pull/1598, so closing this out in favor of using #1596 for tracking.
