### ISSUE TITLE
`ExecuteScript` network call from the Pixie UI fails with ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by thinkhp** [pixie-io/pixie#661]
**Describe the bug**
I deployed pixie using Self hosted, using my own domain name, such as demo.pixie.myorg.me, and applied for a free SSL certificate using ACME, modifying the following file:

k8s/cloud/public/proxy_envoy.yaml
k8s/cloud/public/domain_config.yaml
scripts/create_cloud_secrets.sh

When I access `demo.pixie.myorg.me`, the login is normal and the cluster state is normal, but when I execute the script, it returns an error 
<img width="1463" alt="image" src="https://user-images.githubusercontent.com/26300404/205005348-62bf033d-30ae-46ee-8136-4c502b564fa9.png">
and the browser console shows `POST https://demo.pixie.myorg.me:4444/px.api.vizierpb.VizierService/ExecuteScript net::ERR_CONNECTION_TIMED_OUT`

**Logs**
I'm not sure what the problem is, so just only provide logs, if you need other logs, I'm happy to provide them
 
`cloud-proxy.plc` logs
No ExecuteScript related logs are shown, non-grpc request logs are printed normally
```
10.244.12.0 - - [01/Dec/2022:08:31:52 +0000] "POST /api/graphql HTTP/2.0" 200 143 "https://work.pre.us.adx.pixie.ushareit.me/live/clusters/ads-pre" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
```

`api-server.plc` logs
```
time="2022-12-01T08:28:46Z" level=info msg="[core] Subchannel Connectivity change to IDLE" system=system
time="2022-12-01T08:28:46Z" level=info msg="[balancer] base.baseBalancer: handle SubConn state change: 0xc0007dee00, IDLE" system=system
time="2022-12-01T08:28:46Z" level=info msg="[core] Subchannel Connectivity change to CONNECTING" system=system
time="2022-12-01T08:28:46Z" level=info msg="[core] Subchannel picks a new address \"\" to connect" system=system
time="2022-12-01T08:28:46Z" level=warning msg="[core] grpc: addrConn.createTransport failed to connect to {  <nil> <nil> 0 <nil>}. Err: connection error: desc = \"transport: Error while dialing dial tcp: missing address\"" system=system
time="2022-12-01T08:28:46Z" level=info msg="[core] Subchannel Connectivity change to TRANSIENT_FAILURE" system=system
time="2022-12-01T08:28:46Z" level=info msg="[balancer] base.baseBalancer: handle SubConn state change: 0xc0007dee00, CONNECTING" system=system
time="2022-12-01T08:28:46Z" level=info msg="[balancer] base.baseBalancer: handle SubConn state change: 0xc0007dee00, TRANSIENT_FAILURE" system=system
```

**App information (please complete the following information):**
- Pixie cloud version: `release/cloud/prod/1666129068`
- Pixie CLI version: `0.7.17+Distribution.1f8cdfb.20220816051559.3.jenkins`
- K8s cluster version `Client Version: v1.25.0    Kustomize Version: v4.5.7   Server Version: v1.19.3`
- Node Kernel version `Linux master002 5.4.0-58-generic #64-Ubuntu`
- Browser version `Google Chrome 107.0.5304.121 (arm64)`

**Comment by aimichelle** [comment]
Hi @thinkhp , we may need more information about the modifications you made to those files to help. 

Alternatively, we now have a guide for how to set up Pixie Cloud with your own domain name, so check it out and see if that setup works for you: https://docs.px.dev/installing-pixie/install-guides/production-readiness/

**Comment by thinkhp** [comment]
Thanks, it's because of my network settings

**Comment by keyualiceli** [comment]
I am facing the same problem -- I'm getting 
```
Server error
Http response at 400 or 500 level
```
and my `api-server` logs also look the same.
@thinkhp How were you able to resolve this? What network settings did you change?

**Comment by thinkhp** [comment]
> I am facing the same problem -- I'm getting
> 
> ```
> Server error
> Http response at 400 or 500 level
> ```
> 
> and my `api-server` logs also look the same. @thinkhp How were you able to resolve this? What network settings did you change?

My Pixie UI is located on my company's intranet, and I am accessing the Pixie UI through the VPN of the 飞连 app. When I use the  global mode vpn, the response is back to normal. I guess this is probably because pixie cloud needs to establish a bi-directional connection with the local machine

<img width="396" alt="image" src="https://user-images.githubusercontent.com/26300404/232022177-8b25c390-4b7e-4b5d-b74a-75c5ccc63345.png">
