### ISSUE TITLE
How to modify the mirror address

### ISSUE THREAD

**Issue by clcc2019** [pixie-io/pixie#663]
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/46099295/205234370-af465da4-fa11-4301-8cce-30ea9c7e7a92.png">

<img width="901" alt="image" src="https://user-images.githubusercontent.com/46099295/205234480-65c3d98b-2d7e-471b-83bc-c3aca19ce2b5.png">
I need to modify the mirror address of this job

**Comment by maxlemieux** [comment]
hi @clcc2019, please see: https://docs.pixielabs.ai/reference/admin/deploy-options/#custom-image-registry
