### ISSUE TITLE
Services and pods sometimes don't show up on http traffic on small clusters

### ISSUE THREAD

**Issue by nserrino** [pixie-io/pixie#67]
**Describe the bug**
Filing on behalf of @jhunt. In minikube, sometimes the metadata service gets flaky which leads to no pods or services or http traffic being attributed to pods/services. As a result, many of the live views are blank. 

**To Reproduce**
Run Pixie and px-sock-shop on minikube and go to the px/http_request_stat script, see that there are no results. go to the px/http_data script, see that there are in fact results from px-sock-shop, but with no pod or service attributed.

**Expected behavior**
All of the services and pods to show up.

**Logs**
vizier-metadata

```
time="2020-07-01T17:43:33Z" level=info msg="HTTP Request" req_method=POST req_path="/pl.vizier.services.metadata.MetadataService/GetAgentTableMetadata" resp_code=200 resp_size=70069 resp_status=OK resp_time=8.539313ms
E0701 17:43:34.206016       1 leaderelection.go:356] Failed to update lock: Put https://10.96.0.1:443/api/v1/namespaces/pl/endpoints/metadata-election: context deadline exceeded
I0701 17:43:34.206194       1 leaderelection.go:277] failed to renew lease pl/metadata-election: timed out waiting for the condition
E0701 17:43:34.206443       1 leaderelection.go:296] Failed to release lock: resource name may not be empty
time="2020-07-01T17:43:34Z" level=error msg="leadership lost: vizier-metadata-5b4cf4b6c8-mwpr6"
panic: leadership lost

goroutine 43 [running]:
pixielabs.ai/pixielabs/src/shared/services/election.(*K8sLeaderElectionMgr).runElection.func2()
	src/shared/services/election/election.go:118 +0xe9
k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run.func1(0xc0000c2480)
	external/io_k8s_client_go/tools/leaderelection/leaderelection.go:200 +0x40
k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0xc0000c2480, 0x1cd0220, 0xc000345300)
	external/io_k8s_client_go/tools/leaderelection/leaderelection.go:209 +0x15e
k8s.io/client-go/tools/leaderelection.RunOrDie(0x1cd0220, 0xc0001c80c0, 0x1ce15a0, 0xc0001cc280, 0xb2d05e00, 0x3b9aca00, 0xee6b280, 0x1b0d9b8, 0xc0003d9220, 0xc0001ac130, ...)
	external/io_k8s_client_go/tools/leaderelection/leaderelection.go:221 +0x96
pixielabs.ai/pixielabs/src/shared/services/election.(*K8sLeaderElectionMgr).runElection(0xc0000c0230, 0x1cd0220, 0xc0001c80c0, 0xc0001ac130, 0xc000436020, 0x20)
	src/shared/services/election/election.go:98 +0x2cf
created by pixielabs.ai/pixielabs/src/shared/services/election.(*K8sLeaderElectionMgr).Campaign
	src/shared/services/election/election.go:138 +0x10b
```

Liveness probe failed

**App information (please complete the following information):**
- Pixie version: 0.3.8
- K8s cluster version: v1.18.3

**Additional context**
Minikube, 3-node, running containerd, atop KVM

**Comment by jhunt** [comment]
I tried this again this morning, with a 4-node MK cluster, 8G apiece.  metadata kept crashing because of etcd timeouts.  I tried again with a 4-node, 16G-each MK deployment and it had similar etcd lease contention / context deadline timeouts.  In addition, after the metadata pod crashed ~6 times and then coalesced to a stable state, I still see the failed association in the modified http_data pxl script we were using to troubleshoot.

<img width="1176" alt="Screen Shot 2020-07-02 at 10 00 06 AM" src="https://user-images.githubusercontent.com/20047/86368613-5f8f0900-bc4b-11ea-8761-2125bfb25992.png">

For reference, here's the modified script, in-full:

```

''' HTTP Data Tracer

This script traces all HTTP/HTTP2 data on the cluster for a specified amount of time.
An optional filter prints only those traces that include the specified service name.
'''

import px

# ----------------------------------------------------------------
# Script variables
# ----------------------------------------------------------------

service_matcher = ''
start_time = '-30s'
max_num_records = 100

# ----------------------------------------------------------------
# Implementation
# ----------------------------------------------------------------

df = px.DataFrame(table='http_events', select=['time_', 'upid', 'remote_addr', 'remote_port',
                                               'http_req_method', 'http_req_path',
                                               'http_resp_status', 'http_resp_message',
                                               'http_resp_body',
                                               'http_resp_latency_ns'], start_time=start_time)
df.http_resp_latency_ms = df.http_resp_latency_ns / 1.0E6
df = df.head(n=max_num_records)
df.pod = df.ctx['pod_name']
df.service = df.ctx['service']
px.display(df[['http_req_path', 'pod', 'service']])
```

**Comment by jhunt** [comment]
I've spun down my Minikube clusters and am giving this a go on GKE, on a 4-node GKE cluster make up of n1-standard-4's.

I now see data in the px/services live view.  On a lark, I ran the troubleshooting version of the http_data script, and i still don't see pod / service associations there...  Perhaps there is a bug in the modified script above?
