### ISSUE TITLE
:elf_reader_symbolizer_bpf_test broken with clang15

### ISSUE THREAD

**Issue by yzhao1012** [pixie-io/pixie#670]
**Describe the bug**
The following 2 bpf tests are broken with Clang 15:
//src/stirling/obj_tools:elf_reader_symbolizer_bpf_test

A record of the test run is at:
https://bb.corp.pixielabs.ai/invocation/364d6c47-18e7-453d-8d66-a9eadf192667

**To Reproduce**
1. `arc patch D12623`
2. `cd tools/chef && sudo chef-solo -c solo.rb -j node_workstation.json`
3. Re-login your terminal to pick up the new env vars, which configures to use clang15
4. Run tests

**Expected behavior**
The test should pass

**Screenshots**
<img width="1112" alt="Screen Shot 2022-12-19 at 3 16 01 PM" src="https://user-images.githubusercontent.com/49417456/208546419-7b3423f2-be9f-4599-8720-c8d26a64614b.png">

These are all the failing tests.

**Logs**
N/A

**App information (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by etep** [comment]
We have identified the issue, namely that binaries are compiled (by default) as "position independent" aka PIE with clang-15. Investigating a fix using compiler option `-no-pie`.

**Comment by vihangm** [comment]
This was fixed in bca73fad162850be12736dd4d9be38ea530f6067
