### ISSUE TITLE
Self-Hosted Pixie deploy, The provided credentials are invalid

### ISSUE THREAD

**Issue by ShawnJop** [pixie-io/pixie#671]
**Describe the bug**
Self-Hosted Pixie deploy, all pods are running.
I use chrome to visit https://work.dev.withpixie.dev/. Login to the admin account using [admin@default.com](mailto:admin@default.com) for the email and admin for the password.
notify：The provided credentials are invalid, check for spelling mistakes in your password or username, email address, or phone number.

I don't modify k8s/cloud/base/ory_auth/kratos/kratos_deployment.yaml. 

**To Reproduce**
login https://work.dev.withpixie.dev/

**Expected behavior**
Login succeed

**Screenshots**
![pixie_password](https://user-images.githubusercontent.com/13432226/208891121-3108dfe3-9377-414e-b9e8-38e4eb89921e.png)
![pixie](https://user-images.githubusercontent.com/13432226/208893199-e86a44a0-990d-49ac-ac33-4b93fe685f38.png)

**App information (please complete the following information):**
Version：release/cloud/prod/1670351615
  - gcr.io/pixie-oss/pixie-prod/cloud/auth_server_image:1670351615
  - gcr.io/pixie-oss/pixie-prod/cloud/api_server_image:1670351615
  - ...

**Comment by ShawnJop** [comment]
@vihangm @aimichelle @philkuz @htroisi

**Comment by yang-maple** [comment]
hello! I have a question. The pod  hydra-bdc9bd4fc-9wvrw status is  CrashLoopBackOff 

![图片](https://user-images.githubusercontent.com/90596113/209294544-63ab1b42-240c-4a34-a45e-947068817c98.png)

![图片](https://user-images.githubusercontent.com/90596113/209294619-3d9b69d6-b2ff-40c2-9bae-2480c3483c73.png)

please help me.thanks

**Comment by ShawnJop** [comment]
> hello! I have a question. The pod hydra-bdc9bd4fc-9wvrw status is CrashLoopBackOff
> 
> ![图片](https://user-images.githubusercontent.com/90596113/209294544-63ab1b42-240c-4a34-a45e-947068817c98.png)
> 
> ![图片](https://user-images.githubusercontent.com/90596113/209294619-3d9b69d6-b2ff-40c2-9bae-2480c3483c73.png)
> 
> please help me.thanks

@yang-maple 
You may need to try redeploying.
# kustomize build k8s/cloud/public/ | kubectl delete -f -
# kustomize build k8s/cloud/public/ | kubectl apply -f -

I guess it may be caused by the random startup of the pod. I have also encountered this situation, but not the pod of hydra-*.
Normal after redeployment

**Comment by aimichelle** [comment]
Fixed in https://github.com/pixie-io/pixie/commit/7b714f1ffc8bcb38db356495dc2d4b5cd5bdb790.
