### ISSUE TITLE
Custom registry not used for vizier-operator pod

### ISSUE THREAD

**Issue by maxlemieux** [pixie-io/pixie#673]
**Describe the bug**
Custom registry, although set, is not used for `vizier-operator` pod. It uses this image instead:

```
gcr.io/pixie-oss/pixie-prod/operator/operator_image:0.0.34
```

When `pixie-chart.registry` is set, all pods should use the custom image registry. The `vizier-operator` pod in the `px-operator` namespace does not use the custom registry.

**To Reproduce**
1. Install Pixie with custom registry
2. View description of vizier-operator pod
3. Notice it doesn't use custom registry (and there are probably other errors related to this in a restricted environment)

**Expected behavior**
`vizier-operator` pod uses custom registry to host its app container image.

**App information (please complete the following information):**
- Pixie version: Latest New Relic bundle chart 5.0.2 with Pixie operator version 0.0.34
- K8s cluster version: 1.25/EKS
- Node Kernel version: 5.4.219-126.411.amzn2.x86_64
- Browser version: Chrome latest

**Additional context**
I was able to host the custom image repository at `$registry/gcr.io-pixie-oss-pixie-prod-operator-operator_image` (as with the vizier images) and update the `ClusterServiceVersion` from the `px-operator` namespace to use the custom image. This seems to work, the vizier-operator pod uses the expected image, but I'm not sure if this is the right way to do it.

**Comment by aimichelle** [comment]
Hi @maxlemieux ! Thanks for reporting this. 

Just troubleshooting, did you make sure to run through step 4 in "Collect the OLM Images"? ->
"Locate the operator's csv in the downloaded/pixie-operator/<version>/csv.yaml file. Remove the replaces line and update the image tag for gcr.io/pixie-oss/pixie-prod/operator/operator_image:<version> to your hosted image." 
This part of the instructions is how you tell the index bundle which custom `vizier-operator` to use.

**Comment by maxlemieux** [comment]
Catching up on this - yes, I'd updated the csv.yaml reference at the time.

The issue no longer seems to be reproducible, so we can probably close this.
