### ISSUE TITLE
https://github.com/pixie-io/pixie/blob/main/DEVELOPMENT.md - issue with the cloud secrets

### ISSUE THREAD

**Issue by avingoyal** [pixie-io/pixie#676]
**Describe the bug**
Need addition to the [documentation](https://github.com/pixie-io/pixie/blob/main/DEVELOPMENT.md). Following the steps blindly doesn't work. After running the following command: 
`./scripts/deploy_cloud_prereqs.sh plc-dev dev`
getting the following error:
Credentials path "<workspace path>/private/credentials/k8s/dev" does not exist. Did you slect the right secret type?

**To Reproduce**
1. Checkout pixie repo
2. Follow the steps mentioned here: https://github.com/pixie-io/pixie/blob/main/DEVELOPMENT.md
3. Under the step titled 'Load the config maps and secrets.', run the command:
`./scripts/deploy_cloud_prereqs.sh plc-dev dev`
4. We get the following error:
Credentials path "<workspace path>/private/credentials/k8s/dev" does not exist. Did you slect the right secret type?

**Expected behavior**
The setup steps should work seamlessly.

**Comment by aimichelle** [comment]
Thanks for reporting this! We've just updated `DEVELOPMENT.md` with more up-to-date instructions for how you can run the dev version of cloud using Skaffold.
