### ISSUE TITLE
Add k8ssandra to the demos

### ISSUE THREAD

**Issue by philkuz** [pixie-io/pixie#680]
**Is your feature request related to a problem? Please describe.**
k8ssandra is a great way to demo cassandra data. We should add it to the demos and our release test process.
https://docs-v2.k8ssandra.io/install/local/single-cluster-helm/

**Describe the solution you'd like**
```
px demo deploy k8ssandra
```

**Comment by ddelnano** [comment]
I've been working on this for the Cassandra Town hall I'll be presenting at. The difficult part is allowing the `px demo` command to support the more complex k8ssandra (requires installing crds before hand or integrating with helm).

**Comment by ddelnano** [comment]
With #1376 merged the demo is fully functional. We just need to upload the demo manifests to the production gcs bucket and release the `px` cli for this to be complete.
