### ISSUE TITLE
Mention amd64 build requirement in Custom Image Registry docs

### ISSUE THREAD

**Issue by maxlemieux** [pixie-io/pixie#690]
**Is your feature request related to a problem? Please describe.**
Custom image registry build fails on arm64. This is not warned in the docs.

https://docs.pixielabs.ai/reference/admin/deploy-options/#custom-image-registry

**Describe the solution you'd like**
Docs which state that the build must be performed on amd64, also mentioning Apple M1 chips in that context.

**Comment by JamesMBartlett** [comment]
Pixie know supports `arm64` and `amd64`, and the images we publish are [multiarch](https://docs.docker.com/build/building/multi-platform/). So `amd64` should no longer be a requirement.

**Comment by maxlemieux** [comment]
This issue was relating to the build process for custom image hosting. Part of the OLM build failed on arm64. I will retest when I can and create a new issue with details if needed.

**Comment by JamesMBartlett** [comment]
Sounds good. We recently updated our OLM images to support arm64. There's still one known issue with `kubernetes.io/arch` taints affecting scheduling of some of the OLM jobs, but other than that they should work, so if you run into issues I'd be happy to help.
