### ISSUE TITLE
Deflake `stirling_wrapper_container_bpf_test`

### ISSUE THREAD

**Issue by vihangm** [pixie-io/pixie#700]
`//src/stirling/e2e_tests:stirling_wrapper_container_bpf_test ` has a <90% pass rate in CI.
De-flake the test, run locally with `runs_per_test` set to a large number to ensure that the pass rate is higher than 90% and then re-enable the test in CI by removing the `disabled_flaky_test` tag.

**Comment by ddelnano** [comment]
This is fixed now that #1339 was merged.
