### ISSUE TITLE
Login failed after setting up production-readiness-self-hosted-pixie

### ISSUE THREAD

**Issue by c3-pranjaysagar** [pixie-io/pixie#706]
I used [this](https://docs.px.dev/installing-pixie/install-guides/production-readiness/) Pixie tutorial to set up a production-readiness Self Hosted Environment and I have all the Pods up and running healthy as you can see.

<img width="1674" alt="image" src="https://user-images.githubusercontent.com/99224818/214983216-8531fa61-57b7-446b-8f7e-21e83ca8df62.png">

<img width="509" alt="image" src="https://user-images.githubusercontent.com/99224818/214983232-04cce0bb-74be-4722-b2b2-132deec75987.png">

<img width="845" alt="image" src="https://user-images.githubusercontent.com/99224818/214983265-dd10c201-db5a-4185-8146-42210c531f86.png">

On using the credentials in the document should able to login.

- Browser - Chrome

**Comment by aimichelle** [comment]
Hi @c3-pranjaysagar ! A few questions for debugging purposes: 
- Did you update the default admin username/password? If not, what credentials did you use to try to log in? 
- What version of the cloud have you deployed? You can look at the image tag for one of the pods. 

Thanks!

**Comment by c3-pranjaysagar** [comment]
I didn't updated the default credentials.
I used admin@default.com/admin. credentials provided in documentation.
Version
 Image:          gcr.io/pixie-oss/pixie-prod/cloud/api_server_image:1672961079
    Image ID:       gcr.io/pixie-oss/pixie-prod/cloud/api_server_image@sha256:cdcc6128277f1e064c64e9c7b0a6a0eb88da267b312862bda1067b83e8b4632f
    
    
   Also, is there a way to set our own credentials?

**Comment by c3-pranjaysagar** [comment]
@aimichelle Any update?

**Comment by jihell971** [comment]
Hi, I am also facing the same issue. 
Similarly everything looks OK for the pods and I am using Chrome too.
I tried to change the password and username.
The issue still persist ==> authentication fails

**Comment by jadiaheno** [comment]
Same behaviour here.

**Comment by aimichelle** [comment]
Hi all! We just made a release with a bugfix to address an issue where the admin user wasn't getting created properly. Would you all mind confirming that you no longer run into this in the latest release? Make sure you pull the latest from the repo, and walk through the instructions for deploying the cloud again. Thanks all!

**Comment by jihell971** [comment]
Hi I'm no longer seeing this error. I can authenticate now.

**Comment by vihangm** [comment]
Going to close this as fixed. If you run into other problems, please open a new issue!
