### ISSUE TITLE
BPF tests should be easier to run and be able to run without root 

### ISSUE THREAD

**Issue by zasgar** [pixie-io/pixie#709]
BPF tests currently require root access to run and break out of the bazel sandbox. 

We can try using something like qemu to provide an isolated environment that can be run with bazel support.

**Comment by JamesMBartlett** [comment]
`bazel test --config=qemu-bpf` will now run BPF tests inside of qemu. This configuration still requires the user to have `kvm` permissions but no longer requires root.
