### ISSUE TITLE
Invalid admin login for Air-gapped Pixie 

### ISSUE THREAD

**Issue by keyualiceli** [pixie-io/pixie#763]
**Describe the bug**
In air-gapped pixie using Minikube, all pods are running normally. After navigating to _dev.withpixie.dev_ and using `admin@default.com` as the login identifier and `admin` as the password, we were given the error message 
```
The provided credentials are invalid, check for spelling mistakes in your password or username, email address, or phone number.
```
This seems to be the same issue as in #671 except in the air-gapped version. We tried using the latest release for the images (1674596375) and also the release that resolved the previous issue ([1672961079](https://github.com/pixie-io/pixie/releases/tag/release%2Fcloud%2Fprod%2F1672961079)), but both produced the same error. 

**To Reproduce**
1. Follow the air-gapped installation guide 
2. Update the image versions to 1674596375 instead of latest
3. login https://work.dev.withpixie.dev/
4. use admin@default.com and admin as credentials
5. See error

**Expected behavior**
Should be able to use the admin login 

**Screenshots**
Error page:
![image](https://user-images.githubusercontent.com/56264699/216730389-91b01c57-fcb1-43f1-bade-8441f2e214bb.png)
All k8s pods are running fine:
![image](https://user-images.githubusercontent.com/56264699/216731452-31c7f135-cc7a-4198-8abb-855786df3571.png)

**App information (please complete the following information):**
- K8s cluster version: v1.19.16

**Comment by parkjeongryul** [comment]
Maybe, i think it would be helpful to refer to this? https://github.com/pixie-io/pixie/issues/764

**Comment by jadiaheno** [comment]
Same behaviour here.

**Comment by aimichelle** [comment]
Hi @keyualiceli ! Would you mind sharing the output of your logs from the kratos pod? More specifically `kubectl logs <kratos pod name goes here> -n plc admin-create-if-not-exists `
That container is responsible for creating the admin account, so I'm curious to see what is happening there.

**Comment by keyualiceli** [comment]
Hello @aimichelle! Here is the output it gives me from the logs. These log messages are on looped repeat 

```
+ '[' 000 -eq 200 ]
+ echo 'waiting for https://kratos:4434/admin/health/ready'
waiting for https://kratos:4434/admin/health/ready
+ sleep 2
+ curl -m 0.5 -s -o /dev/null -w '%{http_code}' --cacert /certs/ca.crt https://kratos:4434/admin/health/ready
+ '[' 000 -eq 200 ]
+ echo 'waiting for https://kratos:4434/admin/health/ready'
+ sleep 2
waiting for https://kratos:4434/admin/health/ready
+ curl -m 0.5 -s -o /dev/null -w '%{http_code}' --cacert /certs/ca.crt https://kratos:4434/admin/health/ready
+ '[' 000 -eq 200 ]
+ echo 'waiting for https://kratos:4434/admin/health/ready'
+ sleep 2
waiting for https://kratos:4434/admin/health/ready
+ curl -m 0.5 -s -o /dev/null -w '%{http_code}' --cacert /certs/ca.crt https://kratos:4434/admin/health/ready
+ '[' 000 -eq 200 ]
+ echo 'waiting for https://kratos:4434/admin/health/ready'
+ sleep 2
waiting for https://kratos:4434/admin/health/ready
+ curl -m 0.5 -s -o /dev/null -w '%{http_code}' --cacert /certs/ca.crt https://kratos:4434/admin/health/ready
+ '[' 000 -eq 200 ]
```

**Comment by keyualiceli** [comment]
If it helps, I also logged **kubectl logs <hydra pod name> -n plc client-create-or-update**

```
+ echo 'waiting for https://localhost:4445/health/ready'
+ sleep 2
waiting for https://localhost:4445/health/ready
+ wget --no-check-certificate --spider --quiet --server-response https://localhost:4445/health/ready
+ awk 'NR==1{print $2}'
+ '[' 'can'"'"'t' -eq 200 ]
sh: can't: out of range
+ echo 'waiting for https://localhost:4445/health/ready'
+ sleep 2
waiting for https://localhost:4445/health/ready
+ + awkwget 'NR==1{print $2}' --no-check-certificate
 --spider --quiet --server-response https://localhost:4445/health/ready
waiting for https://localhost:4445/health/ready
+ '[' 'can'"'"'t' -eq 200 ]
sh: can't: out of range
+ echo 'waiting for https://localhost:4445/health/ready'
+ sleep 2
+ wget --no-check-certificate --spider --quiet --server-response https://localhost:4445/health/ready
+ awk 'NR==1{print $2}'
waiting for https://localhost:4445/health/ready
+ '[' 'can'"'"'t' -eq 200 ]
sh: can't: out of range
+ echo 'waiting for https://localhost:4445/health/ready'
+ sleep 2
+ wget --no-check-certificate --spider --quiet --server-response https://localhost:4445/health/ready
+ awk 'NR==1{print $2}'
+ '[' 200 -eq 200 ]
+ CMD='hydra clients update auth-code-client'
+ hydra clients get auth-code-client '--endpoint=https://localhost:4445' --skip-tls-verify
The request failed with the following error message:
{
  "error": "The request could not be authorized",
  "error_description": "The requested OAuth 2.0 client does not exist or you did not provide the necessary credentials"
}

+ '[' 1 -ne 0 ]
+ echo 'Creating client'
+ CMD='hydra clients create --id auth-code-client'
Creating client
+ hydra clients create --id auth-code-client --endpoint https://localhost:4445 --secret 5VMCS1AEwYAoHipiIpWqkAjPIJpIIh3Qq2zCeG2iQD66deGzpnHNy65LDZvrTELN --grant-types authorization_code,refresh_token,implicit --response-types code,id_token,token --scope openid,offline,notifications,gist,vizier --callbacks https://dev.withpixie.dev/oauth/auth/callback --callbacks https://work.dev.withpixie.dev/auth/callback --skip-tls-verify
You should not provide secrets using command line flags, the secret might leak to bash history and similar systems
OAuth 2.0 Client ID: auth-code-client
+ sleep infinity
```

**Comment by ArkadyFukzon** [comment]
Same issue here.
I tried to find the user in postgres from inside the pod, but seems users table is empty (all related tables seem empty), not sure if the initial admin specifically is a special case which doesn't use the database.

**Comment by stobias123** [comment]
I just edited the command on the admin container, remove the cacerts, and replace with insecure. worked well enough.

**Comment by aimichelle** [comment]
Hi all! We just made a release with a bugfix to address an issue where the admin user wasn't getting created properly. Would you all mind confirming that you no longer run into this in the latest release? Make sure you pull the latest from the repo, and walk through the instructions for deploying the cloud again. Thanks all!

**Comment by ArkadyFukzon** [comment]
@aimichelle working for me now, thanks

**Comment by aimichelle** [comment]
Thanks for the confirmation! 
Closing it because it sounds like it has been resolved. Please reopen if you still see this problem occurring in the latest release!
